/*
 * Copyright (c) 2025 TAOS Data, Inc.
 *
 * SPDX-License-Identifier: MIT
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/*
 * GENERATED by driver/native/gen_api_forwarders.py -- do not edit.
 *
 * taosAdapter loads the native client driver at run time (driver/native/tdApiLoader.c)
 * instead of linking libtaos.so, so the public C API the cgo code calls is provided
 * here: per entry point a slot that is filled from the driver once at start-up
 * (tdApiInstallSlots()) and a body that is nothing but `return slot(args);`.  A slot
 * the driver has no counterpart for keeps its <name>_not_provided stub, so the call
 * path carries no check and a missing entry point still fails only its own call.
 *
 * Variadic declarations (taos_options, taos_options_connection) are forwarded with
 * their fixed parameters only: the engine's implementations do not read the variadic
 * arguments (there is no va_arg anywhere in the client), and neither does any caller
 * here.  A declaration that ever does need them has to be forwarded through va_list
 * instead -- the generator does not emit that today.
 */
#include "tdNativeApi.h"

#include <taos.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdio.h>

/* setConfRet taos_set_config(const char *config) */
static setConfRet taos_set_config_not_provided(const char *config) {
  setConfRet ret = {.retCode = -1};
  tdApiNotProvided("taos_set_config");
  return ret;
}
static __typeof__(&taos_set_config) td_api_slot_taos_set_config = taos_set_config_not_provided;
setConfRet taos_set_config(const char *config) { return td_api_slot_taos_set_config(config); }

/* int taos_init(void) */
static int taos_init_not_provided(void) {
  tdApiNotProvided("taos_init");
  return -1;
}
static __typeof__(&taos_init) td_api_slot_taos_init = taos_init_not_provided;
int taos_init(void) { return td_api_slot_taos_init(); }

/* void taos_cleanup(void) */
static void taos_cleanup_not_provided(void) { tdApiNotProvided("taos_cleanup"); }
static __typeof__(&taos_cleanup) td_api_slot_taos_cleanup = taos_cleanup_not_provided;
void taos_cleanup(void) { td_api_slot_taos_cleanup(); }

/* int taos_options(TSDB_OPTION option, const void *arg, ...) */
static int taos_options_not_provided(TSDB_OPTION option, const void *arg, ...) {
  tdApiNotProvided("taos_options");
  return -1;
}
static __typeof__(&taos_options) td_api_slot_taos_options = taos_options_not_provided;
int taos_options(TSDB_OPTION option, const void *arg, ...) { return td_api_slot_taos_options(option, arg); }

/* int taos_options_connection(TAOS *taos, TSDB_OPTION_CONNECTION option, const void *arg, ...) */
static int taos_options_connection_not_provided(TAOS *taos, TSDB_OPTION_CONNECTION option, const void *arg, ...) {
  tdApiNotProvided("taos_options_connection");
  return -1;
}
static __typeof__(&taos_options_connection) td_api_slot_taos_options_connection = taos_options_connection_not_provided;
int taos_options_connection(TAOS *taos, TSDB_OPTION_CONNECTION option, const void *arg, ...) { return td_api_slot_taos_options_connection(taos, option, arg); }

/* void taos_set_option(OPTIONS *options, const char *key, const char *value) */
static void taos_set_option_not_provided(OPTIONS *options, const char *key, const char *value) { tdApiNotProvided("taos_set_option"); }
static __typeof__(&taos_set_option) td_api_slot_taos_set_option = taos_set_option_not_provided;
void taos_set_option(OPTIONS *options, const char *key, const char *value) { td_api_slot_taos_set_option(options, key, value); }

/* TAOS * taos_connect(const char *ip, const char *user, const char *pass, const char *db, uint16_t port) */
static TAOS * taos_connect_not_provided(const char *ip, const char *user, const char *pass, const char *db, uint16_t port) {
  tdApiNotProvided("taos_connect");
  return NULL;
}
static __typeof__(&taos_connect) td_api_slot_taos_connect = taos_connect_not_provided;
TAOS * taos_connect(const char *ip, const char *user, const char *pass, const char *db, uint16_t port) { return td_api_slot_taos_connect(ip, user, pass, db, port); }

/* TAOS * taos_connect_auth(const char *ip, const char *user, const char *auth, const char *db, uint16_t port) */
static TAOS * taos_connect_auth_not_provided(const char *ip, const char *user, const char *auth, const char *db, uint16_t port) {
  tdApiNotProvided("taos_connect_auth");
  return NULL;
}
static __typeof__(&taos_connect_auth) td_api_slot_taos_connect_auth = taos_connect_auth_not_provided;
TAOS * taos_connect_auth(const char *ip, const char *user, const char *auth, const char *db, uint16_t port) { return td_api_slot_taos_connect_auth(ip, user, auth, db, port); }

/* TAOS * taos_connect_with(const OPTIONS *options) */
static TAOS * taos_connect_with_not_provided(const OPTIONS *options) {
  tdApiNotProvided("taos_connect_with");
  return NULL;
}
static __typeof__(&taos_connect_with) td_api_slot_taos_connect_with = taos_connect_with_not_provided;
TAOS * taos_connect_with(const OPTIONS *options) { return td_api_slot_taos_connect_with(options); }

/* TAOS * taos_connect_with_dsn(const char *dsn) */
static TAOS * taos_connect_with_dsn_not_provided(const char *dsn) {
  tdApiNotProvided("taos_connect_with_dsn");
  return NULL;
}
static __typeof__(&taos_connect_with_dsn) td_api_slot_taos_connect_with_dsn = taos_connect_with_dsn_not_provided;
TAOS * taos_connect_with_dsn(const char *dsn) { return td_api_slot_taos_connect_with_dsn(dsn); }

/* TAOS * taos_connect_totp(const char *ip, const char *user, const char *pass, const char* totp, const char *db, uint16_t port) */
static TAOS * taos_connect_totp_not_provided(const char *ip, const char *user, const char *pass, const char* totp, const char *db, uint16_t port) {
  tdApiNotProvided("taos_connect_totp");
  return NULL;
}
static __typeof__(&taos_connect_totp) td_api_slot_taos_connect_totp = taos_connect_totp_not_provided;
TAOS * taos_connect_totp(const char *ip, const char *user, const char *pass, const char* totp, const char *db, uint16_t port) { return td_api_slot_taos_connect_totp(ip, user, pass, totp, db, port); }

/* int taos_connect_test(const char *ip, const char *user, const char *pass, const char* totp, const char *db, uint16_t port) */
static int taos_connect_test_not_provided(const char *ip, const char *user, const char *pass, const char* totp, const char *db, uint16_t port) {
  tdApiNotProvided("taos_connect_test");
  return -1;
}
static __typeof__(&taos_connect_test) td_api_slot_taos_connect_test = taos_connect_test_not_provided;
int taos_connect_test(const char *ip, const char *user, const char *pass, const char* totp, const char *db, uint16_t port) { return td_api_slot_taos_connect_test(ip, user, pass, totp, db, port); }

/* TAOS * taos_connect_token(const char *ip, const char *token, const char *db, uint16_t port) */
static TAOS * taos_connect_token_not_provided(const char *ip, const char *token, const char *db, uint16_t port) {
  tdApiNotProvided("taos_connect_token");
  return NULL;
}
static __typeof__(&taos_connect_token) td_api_slot_taos_connect_token = taos_connect_token_not_provided;
TAOS * taos_connect_token(const char *ip, const char *token, const char *db, uint16_t port) { return td_api_slot_taos_connect_token(ip, token, db, port); }

/* void taos_close(TAOS *taos) */
static void taos_close_not_provided(TAOS *taos) { tdApiNotProvided("taos_close"); }
static __typeof__(&taos_close) td_api_slot_taos_close = taos_close_not_provided;
void taos_close(TAOS *taos) { td_api_slot_taos_close(taos); }

/* int taos_txn_begin(TAOS *taos) */
static int taos_txn_begin_not_provided(TAOS *taos) {
  tdApiNotProvided("taos_txn_begin");
  return -1;
}
static __typeof__(&taos_txn_begin) td_api_slot_taos_txn_begin = taos_txn_begin_not_provided;
int taos_txn_begin(TAOS *taos) { return td_api_slot_taos_txn_begin(taos); }

/* int taos_txn_commit(TAOS *taos) */
static int taos_txn_commit_not_provided(TAOS *taos) {
  tdApiNotProvided("taos_txn_commit");
  return -1;
}
static __typeof__(&taos_txn_commit) td_api_slot_taos_txn_commit = taos_txn_commit_not_provided;
int taos_txn_commit(TAOS *taos) { return td_api_slot_taos_txn_commit(taos); }

/* int taos_txn_rollback(TAOS *taos) */
static int taos_txn_rollback_not_provided(TAOS *taos) {
  tdApiNotProvided("taos_txn_rollback");
  return -1;
}
static __typeof__(&taos_txn_rollback) td_api_slot_taos_txn_rollback = taos_txn_rollback_not_provided;
int taos_txn_rollback(TAOS *taos) { return td_api_slot_taos_txn_rollback(taos); }

/* const char * taos_data_type(int type) */
static const char * taos_data_type_not_provided(int type) {
  tdApiNotProvided("taos_data_type");
  return NULL;
}
static __typeof__(&taos_data_type) td_api_slot_taos_data_type = taos_data_type_not_provided;
const char * taos_data_type(int type) { return td_api_slot_taos_data_type(type); }

/* TAOS_STMT * taos_stmt_init(TAOS *taos) */
static TAOS_STMT * taos_stmt_init_not_provided(TAOS *taos) {
  tdApiNotProvided("taos_stmt_init");
  return NULL;
}
static __typeof__(&taos_stmt_init) td_api_slot_taos_stmt_init = taos_stmt_init_not_provided;
TAOS_STMT * taos_stmt_init(TAOS *taos) { return td_api_slot_taos_stmt_init(taos); }

/* TAOS_STMT * taos_stmt_init_with_reqid(TAOS *taos, int64_t reqid) */
static TAOS_STMT * taos_stmt_init_with_reqid_not_provided(TAOS *taos, int64_t reqid) {
  tdApiNotProvided("taos_stmt_init_with_reqid");
  return NULL;
}
static __typeof__(&taos_stmt_init_with_reqid) td_api_slot_taos_stmt_init_with_reqid = taos_stmt_init_with_reqid_not_provided;
TAOS_STMT * taos_stmt_init_with_reqid(TAOS *taos, int64_t reqid) { return td_api_slot_taos_stmt_init_with_reqid(taos, reqid); }

/* TAOS_STMT * taos_stmt_init_with_options(TAOS *taos, TAOS_STMT_OPTIONS *options) */
static TAOS_STMT * taos_stmt_init_with_options_not_provided(TAOS *taos, TAOS_STMT_OPTIONS *options) {
  tdApiNotProvided("taos_stmt_init_with_options");
  return NULL;
}
static __typeof__(&taos_stmt_init_with_options) td_api_slot_taos_stmt_init_with_options = taos_stmt_init_with_options_not_provided;
TAOS_STMT * taos_stmt_init_with_options(TAOS *taos, TAOS_STMT_OPTIONS *options) { return td_api_slot_taos_stmt_init_with_options(taos, options); }

/* int taos_stmt_prepare(TAOS_STMT *stmt, const char *sql, unsigned long length) */
static int taos_stmt_prepare_not_provided(TAOS_STMT *stmt, const char *sql, unsigned long length) {
  tdApiNotProvided("taos_stmt_prepare");
  return -1;
}
static __typeof__(&taos_stmt_prepare) td_api_slot_taos_stmt_prepare = taos_stmt_prepare_not_provided;
int taos_stmt_prepare(TAOS_STMT *stmt, const char *sql, unsigned long length) { return td_api_slot_taos_stmt_prepare(stmt, sql, length); }

/* int taos_stmt_set_tbname_tags(TAOS_STMT *stmt, const char *name, TAOS_MULTI_BIND *tags) */
static int taos_stmt_set_tbname_tags_not_provided(TAOS_STMT *stmt, const char *name, TAOS_MULTI_BIND *tags) {
  tdApiNotProvided("taos_stmt_set_tbname_tags");
  return -1;
}
static __typeof__(&taos_stmt_set_tbname_tags) td_api_slot_taos_stmt_set_tbname_tags = taos_stmt_set_tbname_tags_not_provided;
int taos_stmt_set_tbname_tags(TAOS_STMT *stmt, const char *name, TAOS_MULTI_BIND *tags) { return td_api_slot_taos_stmt_set_tbname_tags(stmt, name, tags); }

/* int taos_stmt_set_tbname(TAOS_STMT *stmt, const char *name) */
static int taos_stmt_set_tbname_not_provided(TAOS_STMT *stmt, const char *name) {
  tdApiNotProvided("taos_stmt_set_tbname");
  return -1;
}
static __typeof__(&taos_stmt_set_tbname) td_api_slot_taos_stmt_set_tbname = taos_stmt_set_tbname_not_provided;
int taos_stmt_set_tbname(TAOS_STMT *stmt, const char *name) { return td_api_slot_taos_stmt_set_tbname(stmt, name); }

/* int taos_stmt_set_tags(TAOS_STMT *stmt, TAOS_MULTI_BIND *tags) */
static int taos_stmt_set_tags_not_provided(TAOS_STMT *stmt, TAOS_MULTI_BIND *tags) {
  tdApiNotProvided("taos_stmt_set_tags");
  return -1;
}
static __typeof__(&taos_stmt_set_tags) td_api_slot_taos_stmt_set_tags = taos_stmt_set_tags_not_provided;
int taos_stmt_set_tags(TAOS_STMT *stmt, TAOS_MULTI_BIND *tags) { return td_api_slot_taos_stmt_set_tags(stmt, tags); }

/* int taos_stmt_set_sub_tbname(TAOS_STMT *stmt, const char *name) */
static int taos_stmt_set_sub_tbname_not_provided(TAOS_STMT *stmt, const char *name) {
  tdApiNotProvided("taos_stmt_set_sub_tbname");
  return -1;
}
static __typeof__(&taos_stmt_set_sub_tbname) td_api_slot_taos_stmt_set_sub_tbname = taos_stmt_set_sub_tbname_not_provided;
int taos_stmt_set_sub_tbname(TAOS_STMT *stmt, const char *name) { return td_api_slot_taos_stmt_set_sub_tbname(stmt, name); }

/* int taos_stmt_get_tag_fields(TAOS_STMT *stmt, int *fieldNum, TAOS_FIELD_E **fields) */
static int taos_stmt_get_tag_fields_not_provided(TAOS_STMT *stmt, int *fieldNum, TAOS_FIELD_E **fields) {
  tdApiNotProvided("taos_stmt_get_tag_fields");
  return -1;
}
static __typeof__(&taos_stmt_get_tag_fields) td_api_slot_taos_stmt_get_tag_fields = taos_stmt_get_tag_fields_not_provided;
int taos_stmt_get_tag_fields(TAOS_STMT *stmt, int *fieldNum, TAOS_FIELD_E **fields) { return td_api_slot_taos_stmt_get_tag_fields(stmt, fieldNum, fields); }

/* int taos_stmt_get_col_fields(TAOS_STMT *stmt, int *fieldNum, TAOS_FIELD_E **fields) */
static int taos_stmt_get_col_fields_not_provided(TAOS_STMT *stmt, int *fieldNum, TAOS_FIELD_E **fields) {
  tdApiNotProvided("taos_stmt_get_col_fields");
  return -1;
}
static __typeof__(&taos_stmt_get_col_fields) td_api_slot_taos_stmt_get_col_fields = taos_stmt_get_col_fields_not_provided;
int taos_stmt_get_col_fields(TAOS_STMT *stmt, int *fieldNum, TAOS_FIELD_E **fields) { return td_api_slot_taos_stmt_get_col_fields(stmt, fieldNum, fields); }

/* void taos_stmt_reclaim_fields(TAOS_STMT *stmt, TAOS_FIELD_E *fields) */
static void taos_stmt_reclaim_fields_not_provided(TAOS_STMT *stmt, TAOS_FIELD_E *fields) { tdApiNotProvided("taos_stmt_reclaim_fields"); }
static __typeof__(&taos_stmt_reclaim_fields) td_api_slot_taos_stmt_reclaim_fields = taos_stmt_reclaim_fields_not_provided;
void taos_stmt_reclaim_fields(TAOS_STMT *stmt, TAOS_FIELD_E *fields) { td_api_slot_taos_stmt_reclaim_fields(stmt, fields); }

/* int taos_stmt_is_insert(TAOS_STMT *stmt, int *insert) */
static int taos_stmt_is_insert_not_provided(TAOS_STMT *stmt, int *insert) {
  tdApiNotProvided("taos_stmt_is_insert");
  return -1;
}
static __typeof__(&taos_stmt_is_insert) td_api_slot_taos_stmt_is_insert = taos_stmt_is_insert_not_provided;
int taos_stmt_is_insert(TAOS_STMT *stmt, int *insert) { return td_api_slot_taos_stmt_is_insert(stmt, insert); }

/* int taos_stmt_num_params(TAOS_STMT *stmt, int *nums) */
static int taos_stmt_num_params_not_provided(TAOS_STMT *stmt, int *nums) {
  tdApiNotProvided("taos_stmt_num_params");
  return -1;
}
static __typeof__(&taos_stmt_num_params) td_api_slot_taos_stmt_num_params = taos_stmt_num_params_not_provided;
int taos_stmt_num_params(TAOS_STMT *stmt, int *nums) { return td_api_slot_taos_stmt_num_params(stmt, nums); }

/* int taos_stmt_get_param(TAOS_STMT *stmt, int idx, int *type, int *bytes) */
static int taos_stmt_get_param_not_provided(TAOS_STMT *stmt, int idx, int *type, int *bytes) {
  tdApiNotProvided("taos_stmt_get_param");
  return -1;
}
static __typeof__(&taos_stmt_get_param) td_api_slot_taos_stmt_get_param = taos_stmt_get_param_not_provided;
int taos_stmt_get_param(TAOS_STMT *stmt, int idx, int *type, int *bytes) { return td_api_slot_taos_stmt_get_param(stmt, idx, type, bytes); }

/* int taos_stmt_bind_param(TAOS_STMT *stmt, TAOS_MULTI_BIND *bind) */
static int taos_stmt_bind_param_not_provided(TAOS_STMT *stmt, TAOS_MULTI_BIND *bind) {
  tdApiNotProvided("taos_stmt_bind_param");
  return -1;
}
static __typeof__(&taos_stmt_bind_param) td_api_slot_taos_stmt_bind_param = taos_stmt_bind_param_not_provided;
int taos_stmt_bind_param(TAOS_STMT *stmt, TAOS_MULTI_BIND *bind) { return td_api_slot_taos_stmt_bind_param(stmt, bind); }

/* int taos_stmt_bind_param_batch(TAOS_STMT *stmt, TAOS_MULTI_BIND *bind) */
static int taos_stmt_bind_param_batch_not_provided(TAOS_STMT *stmt, TAOS_MULTI_BIND *bind) {
  tdApiNotProvided("taos_stmt_bind_param_batch");
  return -1;
}
static __typeof__(&taos_stmt_bind_param_batch) td_api_slot_taos_stmt_bind_param_batch = taos_stmt_bind_param_batch_not_provided;
int taos_stmt_bind_param_batch(TAOS_STMT *stmt, TAOS_MULTI_BIND *bind) { return td_api_slot_taos_stmt_bind_param_batch(stmt, bind); }

/* int taos_stmt_bind_single_param_batch(TAOS_STMT *stmt, TAOS_MULTI_BIND *bind, int colIdx) */
static int taos_stmt_bind_single_param_batch_not_provided(TAOS_STMT *stmt, TAOS_MULTI_BIND *bind, int colIdx) {
  tdApiNotProvided("taos_stmt_bind_single_param_batch");
  return -1;
}
static __typeof__(&taos_stmt_bind_single_param_batch) td_api_slot_taos_stmt_bind_single_param_batch = taos_stmt_bind_single_param_batch_not_provided;
int taos_stmt_bind_single_param_batch(TAOS_STMT *stmt, TAOS_MULTI_BIND *bind, int colIdx) { return td_api_slot_taos_stmt_bind_single_param_batch(stmt, bind, colIdx); }

/* int taos_stmt_add_batch(TAOS_STMT *stmt) */
static int taos_stmt_add_batch_not_provided(TAOS_STMT *stmt) {
  tdApiNotProvided("taos_stmt_add_batch");
  return -1;
}
static __typeof__(&taos_stmt_add_batch) td_api_slot_taos_stmt_add_batch = taos_stmt_add_batch_not_provided;
int taos_stmt_add_batch(TAOS_STMT *stmt) { return td_api_slot_taos_stmt_add_batch(stmt); }

/* int taos_stmt_execute(TAOS_STMT *stmt) */
static int taos_stmt_execute_not_provided(TAOS_STMT *stmt) {
  tdApiNotProvided("taos_stmt_execute");
  return -1;
}
static __typeof__(&taos_stmt_execute) td_api_slot_taos_stmt_execute = taos_stmt_execute_not_provided;
int taos_stmt_execute(TAOS_STMT *stmt) { return td_api_slot_taos_stmt_execute(stmt); }

/* TAOS_RES * taos_stmt_use_result(TAOS_STMT *stmt) */
static TAOS_RES * taos_stmt_use_result_not_provided(TAOS_STMT *stmt) {
  tdApiNotProvided("taos_stmt_use_result");
  return NULL;
}
static __typeof__(&taos_stmt_use_result) td_api_slot_taos_stmt_use_result = taos_stmt_use_result_not_provided;
TAOS_RES * taos_stmt_use_result(TAOS_STMT *stmt) { return td_api_slot_taos_stmt_use_result(stmt); }

/* int taos_stmt_close(TAOS_STMT *stmt) */
static int taos_stmt_close_not_provided(TAOS_STMT *stmt) {
  tdApiNotProvided("taos_stmt_close");
  return -1;
}
static __typeof__(&taos_stmt_close) td_api_slot_taos_stmt_close = taos_stmt_close_not_provided;
int taos_stmt_close(TAOS_STMT *stmt) { return td_api_slot_taos_stmt_close(stmt); }

/* char * taos_stmt_errstr(TAOS_STMT *stmt) */
static char * taos_stmt_errstr_not_provided(TAOS_STMT *stmt) {
  tdApiNotProvided("taos_stmt_errstr");
  return NULL;
}
static __typeof__(&taos_stmt_errstr) td_api_slot_taos_stmt_errstr = taos_stmt_errstr_not_provided;
char * taos_stmt_errstr(TAOS_STMT *stmt) { return td_api_slot_taos_stmt_errstr(stmt); }

/* int taos_stmt_affected_rows(TAOS_STMT *stmt) */
static int taos_stmt_affected_rows_not_provided(TAOS_STMT *stmt) {
  tdApiNotProvided("taos_stmt_affected_rows");
  return -1;
}
static __typeof__(&taos_stmt_affected_rows) td_api_slot_taos_stmt_affected_rows = taos_stmt_affected_rows_not_provided;
int taos_stmt_affected_rows(TAOS_STMT *stmt) { return td_api_slot_taos_stmt_affected_rows(stmt); }

/* int taos_stmt_affected_rows_once(TAOS_STMT *stmt) */
static int taos_stmt_affected_rows_once_not_provided(TAOS_STMT *stmt) {
  tdApiNotProvided("taos_stmt_affected_rows_once");
  return -1;
}
static __typeof__(&taos_stmt_affected_rows_once) td_api_slot_taos_stmt_affected_rows_once = taos_stmt_affected_rows_once_not_provided;
int taos_stmt_affected_rows_once(TAOS_STMT *stmt) { return td_api_slot_taos_stmt_affected_rows_once(stmt); }

/* TAOS_STMT2 * taos_stmt2_init(TAOS *taos, TAOS_STMT2_OPTION *option) */
static TAOS_STMT2 * taos_stmt2_init_not_provided(TAOS *taos, TAOS_STMT2_OPTION *option) {
  tdApiNotProvided("taos_stmt2_init");
  return NULL;
}
static __typeof__(&taos_stmt2_init) td_api_slot_taos_stmt2_init = taos_stmt2_init_not_provided;
TAOS_STMT2 * taos_stmt2_init(TAOS *taos, TAOS_STMT2_OPTION *option) { return td_api_slot_taos_stmt2_init(taos, option); }

/* int taos_stmt2_prepare(TAOS_STMT2 *stmt, const char *sql, unsigned long length) */
static int taos_stmt2_prepare_not_provided(TAOS_STMT2 *stmt, const char *sql, unsigned long length) {
  tdApiNotProvided("taos_stmt2_prepare");
  return -1;
}
static __typeof__(&taos_stmt2_prepare) td_api_slot_taos_stmt2_prepare = taos_stmt2_prepare_not_provided;
int taos_stmt2_prepare(TAOS_STMT2 *stmt, const char *sql, unsigned long length) { return td_api_slot_taos_stmt2_prepare(stmt, sql, length); }

/* int taos_stmt2_bind_param(TAOS_STMT2 *stmt, TAOS_STMT2_BINDV *bindv, int32_t col_idx) */
static int taos_stmt2_bind_param_not_provided(TAOS_STMT2 *stmt, TAOS_STMT2_BINDV *bindv, int32_t col_idx) {
  tdApiNotProvided("taos_stmt2_bind_param");
  return -1;
}
static __typeof__(&taos_stmt2_bind_param) td_api_slot_taos_stmt2_bind_param = taos_stmt2_bind_param_not_provided;
int taos_stmt2_bind_param(TAOS_STMT2 *stmt, TAOS_STMT2_BINDV *bindv, int32_t col_idx) { return td_api_slot_taos_stmt2_bind_param(stmt, bindv, col_idx); }

/* int taos_stmt2_bind_param_a(TAOS_STMT2 *stmt, TAOS_STMT2_BINDV *bindv, int32_t col_idx, __taos_async_fn_t fp, void *param) */
static int taos_stmt2_bind_param_a_not_provided(TAOS_STMT2 *stmt, TAOS_STMT2_BINDV *bindv, int32_t col_idx, __taos_async_fn_t fp, void *param) {
  tdApiNotProvided("taos_stmt2_bind_param_a");
  return -1;
}
static __typeof__(&taos_stmt2_bind_param_a) td_api_slot_taos_stmt2_bind_param_a = taos_stmt2_bind_param_a_not_provided;
int taos_stmt2_bind_param_a(TAOS_STMT2 *stmt, TAOS_STMT2_BINDV *bindv, int32_t col_idx, __taos_async_fn_t fp, void *param) { return td_api_slot_taos_stmt2_bind_param_a(stmt, bindv, col_idx, fp, param); }

/* int taos_stmt2_bind_param_column(TAOS_STMT2 *stmt, TAOS_STMT2_COLUMN_BINDV *bindv) */
static int taos_stmt2_bind_param_column_not_provided(TAOS_STMT2 *stmt, TAOS_STMT2_COLUMN_BINDV *bindv) {
  tdApiNotProvided("taos_stmt2_bind_param_column");
  return -1;
}
static __typeof__(&taos_stmt2_bind_param_column) td_api_slot_taos_stmt2_bind_param_column = taos_stmt2_bind_param_column_not_provided;
int taos_stmt2_bind_param_column(TAOS_STMT2 *stmt, TAOS_STMT2_COLUMN_BINDV *bindv) { return td_api_slot_taos_stmt2_bind_param_column(stmt, bindv); }

/* int taos_stmt2_bind_param_column_a(TAOS_STMT2 *stmt, TAOS_STMT2_COLUMN_BINDV *bindv, __taos_async_fn_t fp, void *param) */
static int taos_stmt2_bind_param_column_a_not_provided(TAOS_STMT2 *stmt, TAOS_STMT2_COLUMN_BINDV *bindv, __taos_async_fn_t fp, void *param) {
  tdApiNotProvided("taos_stmt2_bind_param_column_a");
  return -1;
}
static __typeof__(&taos_stmt2_bind_param_column_a) td_api_slot_taos_stmt2_bind_param_column_a = taos_stmt2_bind_param_column_a_not_provided;
int taos_stmt2_bind_param_column_a(TAOS_STMT2 *stmt, TAOS_STMT2_COLUMN_BINDV *bindv, __taos_async_fn_t fp, void *param) { return td_api_slot_taos_stmt2_bind_param_column_a(stmt, bindv, fp, param); }

/* int taos_stmt2_exec(TAOS_STMT2 *stmt, int *affected_rows) */
static int taos_stmt2_exec_not_provided(TAOS_STMT2 *stmt, int *affected_rows) {
  tdApiNotProvided("taos_stmt2_exec");
  return -1;
}
static __typeof__(&taos_stmt2_exec) td_api_slot_taos_stmt2_exec = taos_stmt2_exec_not_provided;
int taos_stmt2_exec(TAOS_STMT2 *stmt, int *affected_rows) { return td_api_slot_taos_stmt2_exec(stmt, affected_rows); }

/* int taos_stmt2_close(TAOS_STMT2 *stmt) */
static int taos_stmt2_close_not_provided(TAOS_STMT2 *stmt) {
  tdApiNotProvided("taos_stmt2_close");
  return -1;
}
static __typeof__(&taos_stmt2_close) td_api_slot_taos_stmt2_close = taos_stmt2_close_not_provided;
int taos_stmt2_close(TAOS_STMT2 *stmt) { return td_api_slot_taos_stmt2_close(stmt); }

/* int taos_stmt2_is_insert(TAOS_STMT2 *stmt, int *insert) */
static int taos_stmt2_is_insert_not_provided(TAOS_STMT2 *stmt, int *insert) {
  tdApiNotProvided("taos_stmt2_is_insert");
  return -1;
}
static __typeof__(&taos_stmt2_is_insert) td_api_slot_taos_stmt2_is_insert = taos_stmt2_is_insert_not_provided;
int taos_stmt2_is_insert(TAOS_STMT2 *stmt, int *insert) { return td_api_slot_taos_stmt2_is_insert(stmt, insert); }

/* int taos_stmt2_get_fields(TAOS_STMT2 *stmt, int *count, TAOS_FIELD_ALL **fields) */
static int taos_stmt2_get_fields_not_provided(TAOS_STMT2 *stmt, int *count, TAOS_FIELD_ALL **fields) {
  tdApiNotProvided("taos_stmt2_get_fields");
  return -1;
}
static __typeof__(&taos_stmt2_get_fields) td_api_slot_taos_stmt2_get_fields = taos_stmt2_get_fields_not_provided;
int taos_stmt2_get_fields(TAOS_STMT2 *stmt, int *count, TAOS_FIELD_ALL **fields) { return td_api_slot_taos_stmt2_get_fields(stmt, count, fields); }

/* void taos_stmt2_free_fields(TAOS_STMT2 *stmt, TAOS_FIELD_ALL *fields) */
static void taos_stmt2_free_fields_not_provided(TAOS_STMT2 *stmt, TAOS_FIELD_ALL *fields) { tdApiNotProvided("taos_stmt2_free_fields"); }
static __typeof__(&taos_stmt2_free_fields) td_api_slot_taos_stmt2_free_fields = taos_stmt2_free_fields_not_provided;
void taos_stmt2_free_fields(TAOS_STMT2 *stmt, TAOS_FIELD_ALL *fields) { td_api_slot_taos_stmt2_free_fields(stmt, fields); }

/* TAOS_RES * taos_stmt2_result(TAOS_STMT2 *stmt) */
static TAOS_RES * taos_stmt2_result_not_provided(TAOS_STMT2 *stmt) {
  tdApiNotProvided("taos_stmt2_result");
  return NULL;
}
static __typeof__(&taos_stmt2_result) td_api_slot_taos_stmt2_result = taos_stmt2_result_not_provided;
TAOS_RES * taos_stmt2_result(TAOS_STMT2 *stmt) { return td_api_slot_taos_stmt2_result(stmt); }

/* char * taos_stmt2_error(TAOS_STMT2 *stmt) */
static char * taos_stmt2_error_not_provided(TAOS_STMT2 *stmt) {
  tdApiNotProvided("taos_stmt2_error");
  return NULL;
}
static __typeof__(&taos_stmt2_error) td_api_slot_taos_stmt2_error = taos_stmt2_error_not_provided;
char * taos_stmt2_error(TAOS_STMT2 *stmt) { return td_api_slot_taos_stmt2_error(stmt); }

/* TAOS_RES * taos_query(TAOS *taos, const char *sql) */
static TAOS_RES * taos_query_not_provided(TAOS *taos, const char *sql) {
  tdApiNotProvided("taos_query");
  return NULL;
}
static __typeof__(&taos_query) td_api_slot_taos_query = taos_query_not_provided;
TAOS_RES * taos_query(TAOS *taos, const char *sql) { return td_api_slot_taos_query(taos, sql); }

/* TAOS_RES * taos_query_with_reqid(TAOS *taos, const char *sql, int64_t reqId) */
static TAOS_RES * taos_query_with_reqid_not_provided(TAOS *taos, const char *sql, int64_t reqId) {
  tdApiNotProvided("taos_query_with_reqid");
  return NULL;
}
static __typeof__(&taos_query_with_reqid) td_api_slot_taos_query_with_reqid = taos_query_with_reqid_not_provided;
TAOS_RES * taos_query_with_reqid(TAOS *taos, const char *sql, int64_t reqId) { return td_api_slot_taos_query_with_reqid(taos, sql, reqId); }

/* TAOS_ROW taos_fetch_row(TAOS_RES *res) */
static TAOS_ROW taos_fetch_row_not_provided(TAOS_RES *res) {
  tdApiNotProvided("taos_fetch_row");
  return NULL;
}
static __typeof__(&taos_fetch_row) td_api_slot_taos_fetch_row = taos_fetch_row_not_provided;
TAOS_ROW taos_fetch_row(TAOS_RES *res) { return td_api_slot_taos_fetch_row(res); }

/* int taos_result_precision(TAOS_RES *res) */
static int taos_result_precision_not_provided(TAOS_RES *res) {
  tdApiNotProvided("taos_result_precision");
  return -1;
}
static __typeof__(&taos_result_precision) td_api_slot_taos_result_precision = taos_result_precision_not_provided;
int taos_result_precision(TAOS_RES *res) { return td_api_slot_taos_result_precision(res); }

/* void taos_free_result(TAOS_RES *res) */
static void taos_free_result_not_provided(TAOS_RES *res) { tdApiNotProvided("taos_free_result"); }
static __typeof__(&taos_free_result) td_api_slot_taos_free_result = taos_free_result_not_provided;
void taos_free_result(TAOS_RES *res) { td_api_slot_taos_free_result(res); }

/* void taos_kill_query(TAOS *taos) */
static void taos_kill_query_not_provided(TAOS *taos) { tdApiNotProvided("taos_kill_query"); }
static __typeof__(&taos_kill_query) td_api_slot_taos_kill_query = taos_kill_query_not_provided;
void taos_kill_query(TAOS *taos) { td_api_slot_taos_kill_query(taos); }

/* int taos_field_count(TAOS_RES *res) */
static int taos_field_count_not_provided(TAOS_RES *res) {
  tdApiNotProvided("taos_field_count");
  return -1;
}
static __typeof__(&taos_field_count) td_api_slot_taos_field_count = taos_field_count_not_provided;
int taos_field_count(TAOS_RES *res) { return td_api_slot_taos_field_count(res); }

/* int taos_num_fields(TAOS_RES *res) */
static int taos_num_fields_not_provided(TAOS_RES *res) {
  tdApiNotProvided("taos_num_fields");
  return -1;
}
static __typeof__(&taos_num_fields) td_api_slot_taos_num_fields = taos_num_fields_not_provided;
int taos_num_fields(TAOS_RES *res) { return td_api_slot_taos_num_fields(res); }

/* int taos_affected_rows(TAOS_RES *res) */
static int taos_affected_rows_not_provided(TAOS_RES *res) {
  tdApiNotProvided("taos_affected_rows");
  return -1;
}
static __typeof__(&taos_affected_rows) td_api_slot_taos_affected_rows = taos_affected_rows_not_provided;
int taos_affected_rows(TAOS_RES *res) { return td_api_slot_taos_affected_rows(res); }

/* int64_t taos_affected_rows64(TAOS_RES *res) */
static int64_t taos_affected_rows64_not_provided(TAOS_RES *res) {
  tdApiNotProvided("taos_affected_rows64");
  return -1;
}
static __typeof__(&taos_affected_rows64) td_api_slot_taos_affected_rows64 = taos_affected_rows64_not_provided;
int64_t taos_affected_rows64(TAOS_RES *res) { return td_api_slot_taos_affected_rows64(res); }

/* TAOS_FIELD * taos_fetch_fields(TAOS_RES *res) */
static TAOS_FIELD * taos_fetch_fields_not_provided(TAOS_RES *res) {
  tdApiNotProvided("taos_fetch_fields");
  return NULL;
}
static __typeof__(&taos_fetch_fields) td_api_slot_taos_fetch_fields = taos_fetch_fields_not_provided;
TAOS_FIELD * taos_fetch_fields(TAOS_RES *res) { return td_api_slot_taos_fetch_fields(res); }

/* TAOS_FIELD_E * taos_fetch_fields_e(TAOS_RES *res) */
static TAOS_FIELD_E * taos_fetch_fields_e_not_provided(TAOS_RES *res) {
  tdApiNotProvided("taos_fetch_fields_e");
  return NULL;
}
static __typeof__(&taos_fetch_fields_e) td_api_slot_taos_fetch_fields_e = taos_fetch_fields_e_not_provided;
TAOS_FIELD_E * taos_fetch_fields_e(TAOS_RES *res) { return td_api_slot_taos_fetch_fields_e(res); }

/* int taos_select_db(TAOS *taos, const char *db) */
static int taos_select_db_not_provided(TAOS *taos, const char *db) {
  tdApiNotProvided("taos_select_db");
  return -1;
}
static __typeof__(&taos_select_db) td_api_slot_taos_select_db = taos_select_db_not_provided;
int taos_select_db(TAOS *taos, const char *db) { return td_api_slot_taos_select_db(taos, db); }

/* int taos_print_row(char *str, TAOS_ROW row, TAOS_FIELD *fields, int num_fields) */
static int taos_print_row_not_provided(char *str, TAOS_ROW row, TAOS_FIELD *fields, int num_fields) {
  tdApiNotProvided("taos_print_row");
  return -1;
}
static __typeof__(&taos_print_row) td_api_slot_taos_print_row = taos_print_row_not_provided;
int taos_print_row(char *str, TAOS_ROW row, TAOS_FIELD *fields, int num_fields) { return td_api_slot_taos_print_row(str, row, fields, num_fields); }

/* int taos_print_row_with_size(char *str, uint32_t size, TAOS_ROW row, TAOS_FIELD *fields, int num_fields) */
static int taos_print_row_with_size_not_provided(char *str, uint32_t size, TAOS_ROW row, TAOS_FIELD *fields, int num_fields) {
  tdApiNotProvided("taos_print_row_with_size");
  return -1;
}
static __typeof__(&taos_print_row_with_size) td_api_slot_taos_print_row_with_size = taos_print_row_with_size_not_provided;
int taos_print_row_with_size(char *str, uint32_t size, TAOS_ROW row, TAOS_FIELD *fields, int num_fields) { return td_api_slot_taos_print_row_with_size(str, size, row, fields, num_fields); }

/* void taos_stop_query(TAOS_RES *res) */
static void taos_stop_query_not_provided(TAOS_RES *res) { tdApiNotProvided("taos_stop_query"); }
static __typeof__(&taos_stop_query) td_api_slot_taos_stop_query = taos_stop_query_not_provided;
void taos_stop_query(TAOS_RES *res) { td_api_slot_taos_stop_query(res); }

/* bool taos_is_null(TAOS_RES *res, int32_t row, int32_t col) */
static bool taos_is_null_not_provided(TAOS_RES *res, int32_t row, int32_t col) {
  tdApiNotProvided("taos_is_null");
  return false;
}
static __typeof__(&taos_is_null) td_api_slot_taos_is_null = taos_is_null_not_provided;
bool taos_is_null(TAOS_RES *res, int32_t row, int32_t col) { return td_api_slot_taos_is_null(res, row, col); }

/* int taos_is_null_by_column(TAOS_RES *res, int columnIndex, bool result[], int *rows) */
static int taos_is_null_by_column_not_provided(TAOS_RES *res, int columnIndex, bool result[], int *rows) {
  tdApiNotProvided("taos_is_null_by_column");
  return -1;
}
static __typeof__(&taos_is_null_by_column) td_api_slot_taos_is_null_by_column = taos_is_null_by_column_not_provided;
int taos_is_null_by_column(TAOS_RES *res, int columnIndex, bool result[], int *rows) { return td_api_slot_taos_is_null_by_column(res, columnIndex, result, rows); }

/* bool taos_is_update_query(TAOS_RES *res) */
static bool taos_is_update_query_not_provided(TAOS_RES *res) {
  tdApiNotProvided("taos_is_update_query");
  return false;
}
static __typeof__(&taos_is_update_query) td_api_slot_taos_is_update_query = taos_is_update_query_not_provided;
bool taos_is_update_query(TAOS_RES *res) { return td_api_slot_taos_is_update_query(res); }

/* int taos_fetch_block(TAOS_RES *res, TAOS_ROW *rows) */
static int taos_fetch_block_not_provided(TAOS_RES *res, TAOS_ROW *rows) {
  tdApiNotProvided("taos_fetch_block");
  return -1;
}
static __typeof__(&taos_fetch_block) td_api_slot_taos_fetch_block = taos_fetch_block_not_provided;
int taos_fetch_block(TAOS_RES *res, TAOS_ROW *rows) { return td_api_slot_taos_fetch_block(res, rows); }

/* int taos_fetch_block_s(TAOS_RES *res, int *numOfRows, TAOS_ROW *rows) */
static int taos_fetch_block_s_not_provided(TAOS_RES *res, int *numOfRows, TAOS_ROW *rows) {
  tdApiNotProvided("taos_fetch_block_s");
  return -1;
}
static __typeof__(&taos_fetch_block_s) td_api_slot_taos_fetch_block_s = taos_fetch_block_s_not_provided;
int taos_fetch_block_s(TAOS_RES *res, int *numOfRows, TAOS_ROW *rows) { return td_api_slot_taos_fetch_block_s(res, numOfRows, rows); }

/* int taos_fetch_raw_block(TAOS_RES *res, int *numOfRows, void **pData) */
static int taos_fetch_raw_block_not_provided(TAOS_RES *res, int *numOfRows, void **pData) {
  tdApiNotProvided("taos_fetch_raw_block");
  return -1;
}
static __typeof__(&taos_fetch_raw_block) td_api_slot_taos_fetch_raw_block = taos_fetch_raw_block_not_provided;
int taos_fetch_raw_block(TAOS_RES *res, int *numOfRows, void **pData) { return td_api_slot_taos_fetch_raw_block(res, numOfRows, pData); }

/* int * taos_get_column_data_offset(TAOS_RES *res, int columnIndex) */
static int * taos_get_column_data_offset_not_provided(TAOS_RES *res, int columnIndex) {
  tdApiNotProvided("taos_get_column_data_offset");
  return NULL;
}
static __typeof__(&taos_get_column_data_offset) td_api_slot_taos_get_column_data_offset = taos_get_column_data_offset_not_provided;
int * taos_get_column_data_offset(TAOS_RES *res, int columnIndex) { return td_api_slot_taos_get_column_data_offset(res, columnIndex); }

/* int taos_validate_sql(TAOS *taos, const char *sql) */
static int taos_validate_sql_not_provided(TAOS *taos, const char *sql) {
  tdApiNotProvided("taos_validate_sql");
  return -1;
}
static __typeof__(&taos_validate_sql) td_api_slot_taos_validate_sql = taos_validate_sql_not_provided;
int taos_validate_sql(TAOS *taos, const char *sql) { return td_api_slot_taos_validate_sql(taos, sql); }

/* void taos_reset_current_db(TAOS *taos) */
static void taos_reset_current_db_not_provided(TAOS *taos) { tdApiNotProvided("taos_reset_current_db"); }
static __typeof__(&taos_reset_current_db) td_api_slot_taos_reset_current_db = taos_reset_current_db_not_provided;
void taos_reset_current_db(TAOS *taos) { td_api_slot_taos_reset_current_db(taos); }

/* int * taos_fetch_lengths(TAOS_RES *res) */
static int * taos_fetch_lengths_not_provided(TAOS_RES *res) {
  tdApiNotProvided("taos_fetch_lengths");
  return NULL;
}
static __typeof__(&taos_fetch_lengths) td_api_slot_taos_fetch_lengths = taos_fetch_lengths_not_provided;
int * taos_fetch_lengths(TAOS_RES *res) { return td_api_slot_taos_fetch_lengths(res); }

/* TAOS_ROW * taos_result_block(TAOS_RES *res) */
static TAOS_ROW * taos_result_block_not_provided(TAOS_RES *res) {
  tdApiNotProvided("taos_result_block");
  return NULL;
}
static __typeof__(&taos_result_block) td_api_slot_taos_result_block = taos_result_block_not_provided;
TAOS_ROW * taos_result_block(TAOS_RES *res) { return td_api_slot_taos_result_block(res); }

/* const char * taos_get_server_info(TAOS *taos) */
static const char * taos_get_server_info_not_provided(TAOS *taos) {
  tdApiNotProvided("taos_get_server_info");
  return NULL;
}
static __typeof__(&taos_get_server_info) td_api_slot_taos_get_server_info = taos_get_server_info_not_provided;
const char * taos_get_server_info(TAOS *taos) { return td_api_slot_taos_get_server_info(taos); }

/* const char * taos_get_client_info(void) */
static const char * taos_get_client_info_not_provided(void) {
  tdApiNotProvided("taos_get_client_info");
  return NULL;
}
static __typeof__(&taos_get_client_info) td_api_slot_taos_get_client_info = taos_get_client_info_not_provided;
const char * taos_get_client_info(void) { return td_api_slot_taos_get_client_info(); }

/* int taos_get_current_db(TAOS *taos, char *database, int len, int *required) */
static int taos_get_current_db_not_provided(TAOS *taos, char *database, int len, int *required) {
  tdApiNotProvided("taos_get_current_db");
  return -1;
}
static __typeof__(&taos_get_current_db) td_api_slot_taos_get_current_db = taos_get_current_db_not_provided;
int taos_get_current_db(TAOS *taos, char *database, int len, int *required) { return td_api_slot_taos_get_current_db(taos, database, len, required); }

/* int taos_get_connection_info(TAOS *taos, TSDB_CONNECTION_INFO info, char* buffer, int* len) */
static int taos_get_connection_info_not_provided(TAOS *taos, TSDB_CONNECTION_INFO info, char* buffer, int* len) {
  tdApiNotProvided("taos_get_connection_info");
  return -1;
}
static __typeof__(&taos_get_connection_info) td_api_slot_taos_get_connection_info = taos_get_connection_info_not_provided;
int taos_get_connection_info(TAOS *taos, TSDB_CONNECTION_INFO info, char* buffer, int* len) { return td_api_slot_taos_get_connection_info(taos, info, buffer, len); }

/* void * taos_get_result_tz(TAOS_RES *res) */
static void * taos_get_result_tz_not_provided(TAOS_RES *res) {
  tdApiNotProvided("taos_get_result_tz");
  return NULL;
}
static __typeof__(&taos_get_result_tz) td_api_slot_taos_get_result_tz = taos_get_result_tz_not_provided;
void * taos_get_result_tz(TAOS_RES *res) { return td_api_slot_taos_get_result_tz(res); }

/* const char * taos_errstr(TAOS_RES *res) */
static const char * taos_errstr_not_provided(TAOS_RES *res) {
  tdApiNotProvided("taos_errstr");
  return NULL;
}
static __typeof__(&taos_errstr) td_api_slot_taos_errstr = taos_errstr_not_provided;
const char * taos_errstr(TAOS_RES *res) { return td_api_slot_taos_errstr(res); }

/* int taos_errno(TAOS_RES *res) */
static int taos_errno_not_provided(TAOS_RES *res) {
  tdApiNotProvided("taos_errno");
  return -1;
}
static __typeof__(&taos_errno) td_api_slot_taos_errno = taos_errno_not_provided;
int taos_errno(TAOS_RES *res) { return td_api_slot_taos_errno(res); }

/* void taos_query_a(TAOS *taos, const char *sql, __taos_async_fn_t fp, void *param) */
static void taos_query_a_not_provided(TAOS *taos, const char *sql, __taos_async_fn_t fp, void *param) { tdApiNotProvided("taos_query_a"); }
static __typeof__(&taos_query_a) td_api_slot_taos_query_a = taos_query_a_not_provided;
void taos_query_a(TAOS *taos, const char *sql, __taos_async_fn_t fp, void *param) { td_api_slot_taos_query_a(taos, sql, fp, param); }

/* void taos_query_a_with_reqid(TAOS *taos, const char *sql, __taos_async_fn_t fp, void *param, int64_t reqid) */
static void taos_query_a_with_reqid_not_provided(TAOS *taos, const char *sql, __taos_async_fn_t fp, void *param, int64_t reqid) { tdApiNotProvided("taos_query_a_with_reqid"); }
static __typeof__(&taos_query_a_with_reqid) td_api_slot_taos_query_a_with_reqid = taos_query_a_with_reqid_not_provided;
void taos_query_a_with_reqid(TAOS *taos, const char *sql, __taos_async_fn_t fp, void *param, int64_t reqid) { td_api_slot_taos_query_a_with_reqid(taos, sql, fp, param, reqid); }

/* void taos_fetch_rows_a(TAOS_RES *res, __taos_async_fn_t fp, void *param) */
static void taos_fetch_rows_a_not_provided(TAOS_RES *res, __taos_async_fn_t fp, void *param) { tdApiNotProvided("taos_fetch_rows_a"); }
static __typeof__(&taos_fetch_rows_a) td_api_slot_taos_fetch_rows_a = taos_fetch_rows_a_not_provided;
void taos_fetch_rows_a(TAOS_RES *res, __taos_async_fn_t fp, void *param) { td_api_slot_taos_fetch_rows_a(res, fp, param); }

/* void taos_fetch_raw_block_a(TAOS_RES *res, __taos_async_fn_t fp, void *param) */
static void taos_fetch_raw_block_a_not_provided(TAOS_RES *res, __taos_async_fn_t fp, void *param) { tdApiNotProvided("taos_fetch_raw_block_a"); }
static __typeof__(&taos_fetch_raw_block_a) td_api_slot_taos_fetch_raw_block_a = taos_fetch_raw_block_a_not_provided;
void taos_fetch_raw_block_a(TAOS_RES *res, __taos_async_fn_t fp, void *param) { td_api_slot_taos_fetch_raw_block_a(res, fp, param); }

/* const void * taos_get_raw_block(TAOS_RES *res) */
static const void * taos_get_raw_block_not_provided(TAOS_RES *res) {
  tdApiNotProvided("taos_get_raw_block");
  return NULL;
}
static __typeof__(&taos_get_raw_block) td_api_slot_taos_get_raw_block = taos_get_raw_block_not_provided;
const void * taos_get_raw_block(TAOS_RES *res) { return td_api_slot_taos_get_raw_block(res); }

/* int taos_get_db_route_info(TAOS *taos, const char *db, TAOS_DB_ROUTE_INFO *dbInfo) */
static int taos_get_db_route_info_not_provided(TAOS *taos, const char *db, TAOS_DB_ROUTE_INFO *dbInfo) {
  tdApiNotProvided("taos_get_db_route_info");
  return -1;
}
static __typeof__(&taos_get_db_route_info) td_api_slot_taos_get_db_route_info = taos_get_db_route_info_not_provided;
int taos_get_db_route_info(TAOS *taos, const char *db, TAOS_DB_ROUTE_INFO *dbInfo) { return td_api_slot_taos_get_db_route_info(taos, db, dbInfo); }

/* int taos_get_table_vgId(TAOS *taos, const char *db, const char *table, int *vgId) */
static int taos_get_table_vgId_not_provided(TAOS *taos, const char *db, const char *table, int *vgId) {
  tdApiNotProvided("taos_get_table_vgId");
  return -1;
}
static __typeof__(&taos_get_table_vgId) td_api_slot_taos_get_table_vgId = taos_get_table_vgId_not_provided;
int taos_get_table_vgId(TAOS *taos, const char *db, const char *table, int *vgId) { return td_api_slot_taos_get_table_vgId(taos, db, table, vgId); }

/* int taos_get_tables_vgId(TAOS *taos, const char *db, const char *table[], int tableNum, int *vgId) */
static int taos_get_tables_vgId_not_provided(TAOS *taos, const char *db, const char *table[], int tableNum, int *vgId) {
  tdApiNotProvided("taos_get_tables_vgId");
  return -1;
}
static __typeof__(&taos_get_tables_vgId) td_api_slot_taos_get_tables_vgId = taos_get_tables_vgId_not_provided;
int taos_get_tables_vgId(TAOS *taos, const char *db, const char *table[], int tableNum, int *vgId) { return td_api_slot_taos_get_tables_vgId(taos, db, table, tableNum, vgId); }

/* int taos_load_table_info(TAOS *taos, const char *tableNameList) */
static int taos_load_table_info_not_provided(TAOS *taos, const char *tableNameList) {
  tdApiNotProvided("taos_load_table_info");
  return -1;
}
static __typeof__(&taos_load_table_info) td_api_slot_taos_load_table_info = taos_load_table_info_not_provided;
int taos_load_table_info(TAOS *taos, const char *tableNameList) { return td_api_slot_taos_load_table_info(taos, tableNameList); }

/* void taos_set_hb_quit(int8_t quitByKill) */
static void taos_set_hb_quit_not_provided(int8_t quitByKill) { tdApiNotProvided("taos_set_hb_quit"); }
static __typeof__(&taos_set_hb_quit) td_api_slot_taos_set_hb_quit = taos_set_hb_quit_not_provided;
void taos_set_hb_quit(int8_t quitByKill) { td_api_slot_taos_set_hb_quit(quitByKill); }

/* int taos_set_notify_cb(TAOS *taos, __taos_notify_fn_t fp, void *param, int type) */
static int taos_set_notify_cb_not_provided(TAOS *taos, __taos_notify_fn_t fp, void *param, int type) {
  tdApiNotProvided("taos_set_notify_cb");
  return -1;
}
static __typeof__(&taos_set_notify_cb) td_api_slot_taos_set_notify_cb = taos_set_notify_cb_not_provided;
int taos_set_notify_cb(TAOS *taos, __taos_notify_fn_t fp, void *param, int type) { return td_api_slot_taos_set_notify_cb(taos, fp, param, type); }

/* void taos_fetch_whitelist_a(TAOS *taos, __taos_async_whitelist_fn_t fp, void *param) */
static void taos_fetch_whitelist_a_not_provided(TAOS *taos, __taos_async_whitelist_fn_t fp, void *param) { tdApiNotProvided("taos_fetch_whitelist_a"); }
static __typeof__(&taos_fetch_whitelist_a) td_api_slot_taos_fetch_whitelist_a = taos_fetch_whitelist_a_not_provided;
void taos_fetch_whitelist_a(TAOS *taos, __taos_async_whitelist_fn_t fp, void *param) { td_api_slot_taos_fetch_whitelist_a(taos, fp, param); }

/* void taos_fetch_whitelist_dual_stack_a(TAOS *taos, __taos_async_whitelist_dual_stack_fn_t fp, void *param) */
static void taos_fetch_whitelist_dual_stack_a_not_provided(TAOS *taos, __taos_async_whitelist_dual_stack_fn_t fp, void *param) { tdApiNotProvided("taos_fetch_whitelist_dual_stack_a"); }
static __typeof__(&taos_fetch_whitelist_dual_stack_a) td_api_slot_taos_fetch_whitelist_dual_stack_a = taos_fetch_whitelist_dual_stack_a_not_provided;
void taos_fetch_whitelist_dual_stack_a(TAOS *taos, __taos_async_whitelist_dual_stack_fn_t fp, void *param) { td_api_slot_taos_fetch_whitelist_dual_stack_a(taos, fp, param); }

/* void taos_fetch_ip_whitelist_a(TAOS *taos, __taos_async_ip_whitelist_fn_t fp, void *param) */
static void taos_fetch_ip_whitelist_a_not_provided(TAOS *taos, __taos_async_ip_whitelist_fn_t fp, void *param) { tdApiNotProvided("taos_fetch_ip_whitelist_a"); }
static __typeof__(&taos_fetch_ip_whitelist_a) td_api_slot_taos_fetch_ip_whitelist_a = taos_fetch_ip_whitelist_a_not_provided;
void taos_fetch_ip_whitelist_a(TAOS *taos, __taos_async_ip_whitelist_fn_t fp, void *param) { td_api_slot_taos_fetch_ip_whitelist_a(taos, fp, param); }

/* void taos_fetch_datetime_whitelist_a(TAOS *taos, __taos_async_datetime_whitelist_fn_t fp, void *param) */
static void taos_fetch_datetime_whitelist_a_not_provided(TAOS *taos, __taos_async_datetime_whitelist_fn_t fp, void *param) { tdApiNotProvided("taos_fetch_datetime_whitelist_a"); }
static __typeof__(&taos_fetch_datetime_whitelist_a) td_api_slot_taos_fetch_datetime_whitelist_a = taos_fetch_datetime_whitelist_a_not_provided;
void taos_fetch_datetime_whitelist_a(TAOS *taos, __taos_async_datetime_whitelist_fn_t fp, void *param) { td_api_slot_taos_fetch_datetime_whitelist_a(taos, fp, param); }

/* int taos_set_conn_mode(TAOS *taos, int mode, int value) */
static int taos_set_conn_mode_not_provided(TAOS *taos, int mode, int value) {
  tdApiNotProvided("taos_set_conn_mode");
  return -1;
}
static __typeof__(&taos_set_conn_mode) td_api_slot_taos_set_conn_mode = taos_set_conn_mode_not_provided;
int taos_set_conn_mode(TAOS *taos, int mode, int value) { return td_api_slot_taos_set_conn_mode(taos, mode, value); }

/* TAOS_RES * taos_schemaless_insert(TAOS *taos, char *lines[], int numLines, int protocol, int precision) */
static TAOS_RES * taos_schemaless_insert_not_provided(TAOS *taos, char *lines[], int numLines, int protocol, int precision) {
  tdApiNotProvided("taos_schemaless_insert");
  return NULL;
}
static __typeof__(&taos_schemaless_insert) td_api_slot_taos_schemaless_insert = taos_schemaless_insert_not_provided;
TAOS_RES * taos_schemaless_insert(TAOS *taos, char *lines[], int numLines, int protocol, int precision) { return td_api_slot_taos_schemaless_insert(taos, lines, numLines, protocol, precision); }

/* TAOS_RES * taos_schemaless_insert_with_reqid(TAOS *taos, char *lines[], int numLines, int protocol, int precision, int64_t reqid) */
static TAOS_RES * taos_schemaless_insert_with_reqid_not_provided(TAOS *taos, char *lines[], int numLines, int protocol, int precision, int64_t reqid) {
  tdApiNotProvided("taos_schemaless_insert_with_reqid");
  return NULL;
}
static __typeof__(&taos_schemaless_insert_with_reqid) td_api_slot_taos_schemaless_insert_with_reqid = taos_schemaless_insert_with_reqid_not_provided;
TAOS_RES * taos_schemaless_insert_with_reqid(TAOS *taos, char *lines[], int numLines, int protocol, int precision, int64_t reqid) { return td_api_slot_taos_schemaless_insert_with_reqid(taos, lines, numLines, protocol, precision, reqid); }

/* TAOS_RES * taos_schemaless_insert_raw(TAOS *taos, char *lines, int len, int32_t *totalRows, int protocol, int precision) */
static TAOS_RES * taos_schemaless_insert_raw_not_provided(TAOS *taos, char *lines, int len, int32_t *totalRows, int protocol, int precision) {
  tdApiNotProvided("taos_schemaless_insert_raw");
  return NULL;
}
static __typeof__(&taos_schemaless_insert_raw) td_api_slot_taos_schemaless_insert_raw = taos_schemaless_insert_raw_not_provided;
TAOS_RES * taos_schemaless_insert_raw(TAOS *taos, char *lines, int len, int32_t *totalRows, int protocol, int precision) { return td_api_slot_taos_schemaless_insert_raw(taos, lines, len, totalRows, protocol, precision); }

/* TAOS_RES * taos_schemaless_insert_raw_with_reqid(TAOS *taos, char *lines, int len, int32_t *totalRows, int protocol, int precision, int64_t reqid) */
static TAOS_RES * taos_schemaless_insert_raw_with_reqid_not_provided(TAOS *taos, char *lines, int len, int32_t *totalRows, int protocol, int precision, int64_t reqid) {
  tdApiNotProvided("taos_schemaless_insert_raw_with_reqid");
  return NULL;
}
static __typeof__(&taos_schemaless_insert_raw_with_reqid) td_api_slot_taos_schemaless_insert_raw_with_reqid = taos_schemaless_insert_raw_with_reqid_not_provided;
TAOS_RES * taos_schemaless_insert_raw_with_reqid(TAOS *taos, char *lines, int len, int32_t *totalRows, int protocol, int precision, int64_t reqid) { return td_api_slot_taos_schemaless_insert_raw_with_reqid(taos, lines, len, totalRows, protocol, precision, reqid); }

/* TAOS_RES * taos_schemaless_insert_ttl(TAOS *taos, char *lines[], int numLines, int protocol, int precision, int32_t ttl) */
static TAOS_RES * taos_schemaless_insert_ttl_not_provided(TAOS *taos, char *lines[], int numLines, int protocol, int precision, int32_t ttl) {
  tdApiNotProvided("taos_schemaless_insert_ttl");
  return NULL;
}
static __typeof__(&taos_schemaless_insert_ttl) td_api_slot_taos_schemaless_insert_ttl = taos_schemaless_insert_ttl_not_provided;
TAOS_RES * taos_schemaless_insert_ttl(TAOS *taos, char *lines[], int numLines, int protocol, int precision, int32_t ttl) { return td_api_slot_taos_schemaless_insert_ttl(taos, lines, numLines, protocol, precision, ttl); }

/* TAOS_RES * taos_schemaless_insert_ttl_with_reqid(TAOS *taos, char *lines[], int numLines, int protocol, int precision, int32_t ttl, int64_t reqid) */
static TAOS_RES * taos_schemaless_insert_ttl_with_reqid_not_provided(TAOS *taos, char *lines[], int numLines, int protocol, int precision, int32_t ttl, int64_t reqid) {
  tdApiNotProvided("taos_schemaless_insert_ttl_with_reqid");
  return NULL;
}
static __typeof__(&taos_schemaless_insert_ttl_with_reqid) td_api_slot_taos_schemaless_insert_ttl_with_reqid = taos_schemaless_insert_ttl_with_reqid_not_provided;
TAOS_RES * taos_schemaless_insert_ttl_with_reqid(TAOS *taos, char *lines[], int numLines, int protocol, int precision, int32_t ttl, int64_t reqid) { return td_api_slot_taos_schemaless_insert_ttl_with_reqid(taos, lines, numLines, protocol, precision, ttl, reqid); }

/* TAOS_RES * taos_schemaless_insert_raw_ttl(TAOS *taos, char *lines, int len, int32_t *totalRows, int protocol, int precision, int32_t ttl) */
static TAOS_RES * taos_schemaless_insert_raw_ttl_not_provided(TAOS *taos, char *lines, int len, int32_t *totalRows, int protocol, int precision, int32_t ttl) {
  tdApiNotProvided("taos_schemaless_insert_raw_ttl");
  return NULL;
}
static __typeof__(&taos_schemaless_insert_raw_ttl) td_api_slot_taos_schemaless_insert_raw_ttl = taos_schemaless_insert_raw_ttl_not_provided;
TAOS_RES * taos_schemaless_insert_raw_ttl(TAOS *taos, char *lines, int len, int32_t *totalRows, int protocol, int precision, int32_t ttl) { return td_api_slot_taos_schemaless_insert_raw_ttl(taos, lines, len, totalRows, protocol, precision, ttl); }

/* TAOS_RES * taos_schemaless_insert_raw_ttl_with_reqid(TAOS *taos, char *lines, int len, int32_t *totalRows, int protocol, int precision, int32_t ttl, int64_t reqid) */
static TAOS_RES * taos_schemaless_insert_raw_ttl_with_reqid_not_provided(TAOS *taos, char *lines, int len, int32_t *totalRows, int protocol, int precision, int32_t ttl, int64_t reqid) {
  tdApiNotProvided("taos_schemaless_insert_raw_ttl_with_reqid");
  return NULL;
}
static __typeof__(&taos_schemaless_insert_raw_ttl_with_reqid) td_api_slot_taos_schemaless_insert_raw_ttl_with_reqid = taos_schemaless_insert_raw_ttl_with_reqid_not_provided;
TAOS_RES * taos_schemaless_insert_raw_ttl_with_reqid(TAOS *taos, char *lines, int len, int32_t *totalRows, int protocol, int precision, int32_t ttl, int64_t reqid) { return td_api_slot_taos_schemaless_insert_raw_ttl_with_reqid(taos, lines, len, totalRows, protocol, precision, ttl, reqid); }

/* TAOS_RES * taos_schemaless_insert_raw_ttl_with_reqid_tbname_key(TAOS *taos, char *lines, int len, int32_t *totalRows, int protocol, int precision, int32_t ttl, int64_t reqid, char *tbnameKey) */
static TAOS_RES * taos_schemaless_insert_raw_ttl_with_reqid_tbname_key_not_provided(TAOS *taos, char *lines, int len, int32_t *totalRows, int protocol, int precision, int32_t ttl, int64_t reqid, char *tbnameKey) {
  tdApiNotProvided("taos_schemaless_insert_raw_ttl_with_reqid_tbname_key");
  return NULL;
}
static __typeof__(&taos_schemaless_insert_raw_ttl_with_reqid_tbname_key) td_api_slot_taos_schemaless_insert_raw_ttl_with_reqid_tbname_key = taos_schemaless_insert_raw_ttl_with_reqid_tbname_key_not_provided;
TAOS_RES * taos_schemaless_insert_raw_ttl_with_reqid_tbname_key(TAOS *taos, char *lines, int len, int32_t *totalRows, int protocol, int precision, int32_t ttl, int64_t reqid, char *tbnameKey) { return td_api_slot_taos_schemaless_insert_raw_ttl_with_reqid_tbname_key(taos, lines, len, totalRows, protocol, precision, ttl, reqid, tbnameKey); }

/* TAOS_RES * taos_schemaless_insert_ttl_with_reqid_tbname_key(TAOS *taos, char *lines[], int numLines, int protocol, int precision, int32_t ttl, int64_t reqid, char *tbnameKey) */
static TAOS_RES * taos_schemaless_insert_ttl_with_reqid_tbname_key_not_provided(TAOS *taos, char *lines[], int numLines, int protocol, int precision, int32_t ttl, int64_t reqid, char *tbnameKey) {
  tdApiNotProvided("taos_schemaless_insert_ttl_with_reqid_tbname_key");
  return NULL;
}
static __typeof__(&taos_schemaless_insert_ttl_with_reqid_tbname_key) td_api_slot_taos_schemaless_insert_ttl_with_reqid_tbname_key = taos_schemaless_insert_ttl_with_reqid_tbname_key_not_provided;
TAOS_RES * taos_schemaless_insert_ttl_with_reqid_tbname_key(TAOS *taos, char *lines[], int numLines, int protocol, int precision, int32_t ttl, int64_t reqid, char *tbnameKey) { return td_api_slot_taos_schemaless_insert_ttl_with_reqid_tbname_key(taos, lines, numLines, protocol, precision, ttl, reqid, tbnameKey); }

/* tmq_conf_t * tmq_conf_new(void) */
static tmq_conf_t * tmq_conf_new_not_provided(void) {
  tdApiNotProvided("tmq_conf_new");
  return NULL;
}
static __typeof__(&tmq_conf_new) td_api_slot_tmq_conf_new = tmq_conf_new_not_provided;
tmq_conf_t * tmq_conf_new(void) { return td_api_slot_tmq_conf_new(); }

/* tmq_conf_res_t tmq_conf_set(tmq_conf_t *conf, const char *key, const char *value) */
static tmq_conf_res_t tmq_conf_set_not_provided(tmq_conf_t *conf, const char *key, const char *value) {
  tdApiNotProvided("tmq_conf_set");
  return -1;
}
static __typeof__(&tmq_conf_set) td_api_slot_tmq_conf_set = tmq_conf_set_not_provided;
tmq_conf_res_t tmq_conf_set(tmq_conf_t *conf, const char *key, const char *value) { return td_api_slot_tmq_conf_set(conf, key, value); }

/* void tmq_conf_destroy(tmq_conf_t *conf) */
static void tmq_conf_destroy_not_provided(tmq_conf_t *conf) { tdApiNotProvided("tmq_conf_destroy"); }
static __typeof__(&tmq_conf_destroy) td_api_slot_tmq_conf_destroy = tmq_conf_destroy_not_provided;
void tmq_conf_destroy(tmq_conf_t *conf) { td_api_slot_tmq_conf_destroy(conf); }

/* void tmq_conf_set_auto_commit_cb(tmq_conf_t *conf, tmq_commit_cb *cb, void *param) */
static void tmq_conf_set_auto_commit_cb_not_provided(tmq_conf_t *conf, tmq_commit_cb *cb, void *param) { tdApiNotProvided("tmq_conf_set_auto_commit_cb"); }
static __typeof__(&tmq_conf_set_auto_commit_cb) td_api_slot_tmq_conf_set_auto_commit_cb = tmq_conf_set_auto_commit_cb_not_provided;
void tmq_conf_set_auto_commit_cb(tmq_conf_t *conf, tmq_commit_cb *cb, void *param) { td_api_slot_tmq_conf_set_auto_commit_cb(conf, cb, param); }

/* tmq_list_t * tmq_list_new(void) */
static tmq_list_t * tmq_list_new_not_provided(void) {
  tdApiNotProvided("tmq_list_new");
  return NULL;
}
static __typeof__(&tmq_list_new) td_api_slot_tmq_list_new = tmq_list_new_not_provided;
tmq_list_t * tmq_list_new(void) { return td_api_slot_tmq_list_new(); }

/* int32_t tmq_list_append(tmq_list_t *arg0, const char *arg1) */
static int32_t tmq_list_append_not_provided(tmq_list_t *arg0, const char *arg1) {
  tdApiNotProvided("tmq_list_append");
  return -1;
}
static __typeof__(&tmq_list_append) td_api_slot_tmq_list_append = tmq_list_append_not_provided;
int32_t tmq_list_append(tmq_list_t *arg0, const char *arg1) { return td_api_slot_tmq_list_append(arg0, arg1); }

/* void tmq_list_destroy(tmq_list_t *arg0) */
static void tmq_list_destroy_not_provided(tmq_list_t *arg0) { tdApiNotProvided("tmq_list_destroy"); }
static __typeof__(&tmq_list_destroy) td_api_slot_tmq_list_destroy = tmq_list_destroy_not_provided;
void tmq_list_destroy(tmq_list_t *arg0) { td_api_slot_tmq_list_destroy(arg0); }

/* int32_t tmq_list_get_size(const tmq_list_t *arg0) */
static int32_t tmq_list_get_size_not_provided(const tmq_list_t *arg0) {
  tdApiNotProvided("tmq_list_get_size");
  return -1;
}
static __typeof__(&tmq_list_get_size) td_api_slot_tmq_list_get_size = tmq_list_get_size_not_provided;
int32_t tmq_list_get_size(const tmq_list_t *arg0) { return td_api_slot_tmq_list_get_size(arg0); }

/* char ** tmq_list_to_c_array(const tmq_list_t *arg0) */
static char ** tmq_list_to_c_array_not_provided(const tmq_list_t *arg0) {
  tdApiNotProvided("tmq_list_to_c_array");
  return NULL;
}
static __typeof__(&tmq_list_to_c_array) td_api_slot_tmq_list_to_c_array = tmq_list_to_c_array_not_provided;
char ** tmq_list_to_c_array(const tmq_list_t *arg0) { return td_api_slot_tmq_list_to_c_array(arg0); }

/* tmq_t * tmq_consumer_new(tmq_conf_t *conf, char *errstr, int32_t errstrLen) */
static tmq_t * tmq_consumer_new_not_provided(tmq_conf_t *conf, char *errstr, int32_t errstrLen) {
  tdApiNotProvided("tmq_consumer_new");
  return NULL;
}
static __typeof__(&tmq_consumer_new) td_api_slot_tmq_consumer_new = tmq_consumer_new_not_provided;
tmq_t * tmq_consumer_new(tmq_conf_t *conf, char *errstr, int32_t errstrLen) { return td_api_slot_tmq_consumer_new(conf, errstr, errstrLen); }

/* int32_t tmq_subscribe(tmq_t *tmq, const tmq_list_t *topic_list) */
static int32_t tmq_subscribe_not_provided(tmq_t *tmq, const tmq_list_t *topic_list) {
  tdApiNotProvided("tmq_subscribe");
  return -1;
}
static __typeof__(&tmq_subscribe) td_api_slot_tmq_subscribe = tmq_subscribe_not_provided;
int32_t tmq_subscribe(tmq_t *tmq, const tmq_list_t *topic_list) { return td_api_slot_tmq_subscribe(tmq, topic_list); }

/* int32_t tmq_unsubscribe(tmq_t *tmq) */
static int32_t tmq_unsubscribe_not_provided(tmq_t *tmq) {
  tdApiNotProvided("tmq_unsubscribe");
  return -1;
}
static __typeof__(&tmq_unsubscribe) td_api_slot_tmq_unsubscribe = tmq_unsubscribe_not_provided;
int32_t tmq_unsubscribe(tmq_t *tmq) { return td_api_slot_tmq_unsubscribe(tmq); }

/* int32_t tmq_subscription(tmq_t *tmq, tmq_list_t **topics) */
static int32_t tmq_subscription_not_provided(tmq_t *tmq, tmq_list_t **topics) {
  tdApiNotProvided("tmq_subscription");
  return -1;
}
static __typeof__(&tmq_subscription) td_api_slot_tmq_subscription = tmq_subscription_not_provided;
int32_t tmq_subscription(tmq_t *tmq, tmq_list_t **topics) { return td_api_slot_tmq_subscription(tmq, topics); }

/* TAOS_RES * tmq_consumer_poll(tmq_t *tmq, int64_t timeout) */
static TAOS_RES * tmq_consumer_poll_not_provided(tmq_t *tmq, int64_t timeout) {
  tdApiNotProvided("tmq_consumer_poll");
  return NULL;
}
static __typeof__(&tmq_consumer_poll) td_api_slot_tmq_consumer_poll = tmq_consumer_poll_not_provided;
TAOS_RES * tmq_consumer_poll(tmq_t *tmq, int64_t timeout) { return td_api_slot_tmq_consumer_poll(tmq, timeout); }

/* int32_t tmq_consumer_close(tmq_t *tmq) */
static int32_t tmq_consumer_close_not_provided(tmq_t *tmq) {
  tdApiNotProvided("tmq_consumer_close");
  return -1;
}
static __typeof__(&tmq_consumer_close) td_api_slot_tmq_consumer_close = tmq_consumer_close_not_provided;
int32_t tmq_consumer_close(tmq_t *tmq) { return td_api_slot_tmq_consumer_close(tmq); }

/* int32_t tmq_commit_sync(tmq_t *tmq, const TAOS_RES *msg) */
static int32_t tmq_commit_sync_not_provided(tmq_t *tmq, const TAOS_RES *msg) {
  tdApiNotProvided("tmq_commit_sync");
  return -1;
}
static __typeof__(&tmq_commit_sync) td_api_slot_tmq_commit_sync = tmq_commit_sync_not_provided;
int32_t tmq_commit_sync(tmq_t *tmq, const TAOS_RES *msg) { return td_api_slot_tmq_commit_sync(tmq, msg); }

/* void tmq_commit_async(tmq_t *tmq, const TAOS_RES *msg, tmq_commit_cb *cb, void *param) */
static void tmq_commit_async_not_provided(tmq_t *tmq, const TAOS_RES *msg, tmq_commit_cb *cb, void *param) { tdApiNotProvided("tmq_commit_async"); }
static __typeof__(&tmq_commit_async) td_api_slot_tmq_commit_async = tmq_commit_async_not_provided;
void tmq_commit_async(tmq_t *tmq, const TAOS_RES *msg, tmq_commit_cb *cb, void *param) { td_api_slot_tmq_commit_async(tmq, msg, cb, param); }

/* int32_t tmq_commit_offset_sync(tmq_t *tmq, const char *pTopicName, int32_t vgId, int64_t offset) */
static int32_t tmq_commit_offset_sync_not_provided(tmq_t *tmq, const char *pTopicName, int32_t vgId, int64_t offset) {
  tdApiNotProvided("tmq_commit_offset_sync");
  return -1;
}
static __typeof__(&tmq_commit_offset_sync) td_api_slot_tmq_commit_offset_sync = tmq_commit_offset_sync_not_provided;
int32_t tmq_commit_offset_sync(tmq_t *tmq, const char *pTopicName, int32_t vgId, int64_t offset) { return td_api_slot_tmq_commit_offset_sync(tmq, pTopicName, vgId, offset); }

/* void tmq_commit_offset_async(tmq_t *tmq, const char *pTopicName, int32_t vgId, int64_t offset, tmq_commit_cb *cb, void *param) */
static void tmq_commit_offset_async_not_provided(tmq_t *tmq, const char *pTopicName, int32_t vgId, int64_t offset, tmq_commit_cb *cb, void *param) { tdApiNotProvided("tmq_commit_offset_async"); }
static __typeof__(&tmq_commit_offset_async) td_api_slot_tmq_commit_offset_async = tmq_commit_offset_async_not_provided;
void tmq_commit_offset_async(tmq_t *tmq, const char *pTopicName, int32_t vgId, int64_t offset, tmq_commit_cb *cb, void *param) { td_api_slot_tmq_commit_offset_async(tmq, pTopicName, vgId, offset, cb, param); }

/* int32_t tmq_get_topic_assignment(tmq_t *tmq, const char *pTopicName, tmq_topic_assignment **assignment, int32_t *numOfAssignment) */
static int32_t tmq_get_topic_assignment_not_provided(tmq_t *tmq, const char *pTopicName, tmq_topic_assignment **assignment, int32_t *numOfAssignment) {
  tdApiNotProvided("tmq_get_topic_assignment");
  return -1;
}
static __typeof__(&tmq_get_topic_assignment) td_api_slot_tmq_get_topic_assignment = tmq_get_topic_assignment_not_provided;
int32_t tmq_get_topic_assignment(tmq_t *tmq, const char *pTopicName, tmq_topic_assignment **assignment, int32_t *numOfAssignment) { return td_api_slot_tmq_get_topic_assignment(tmq, pTopicName, assignment, numOfAssignment); }

/* void tmq_free_assignment(tmq_topic_assignment *pAssignment) */
static void tmq_free_assignment_not_provided(tmq_topic_assignment *pAssignment) { tdApiNotProvided("tmq_free_assignment"); }
static __typeof__(&tmq_free_assignment) td_api_slot_tmq_free_assignment = tmq_free_assignment_not_provided;
void tmq_free_assignment(tmq_topic_assignment *pAssignment) { td_api_slot_tmq_free_assignment(pAssignment); }

/* int32_t tmq_offset_seek(tmq_t *tmq, const char *pTopicName, int32_t vgId, int64_t offset) */
static int32_t tmq_offset_seek_not_provided(tmq_t *tmq, const char *pTopicName, int32_t vgId, int64_t offset) {
  tdApiNotProvided("tmq_offset_seek");
  return -1;
}
static __typeof__(&tmq_offset_seek) td_api_slot_tmq_offset_seek = tmq_offset_seek_not_provided;
int32_t tmq_offset_seek(tmq_t *tmq, const char *pTopicName, int32_t vgId, int64_t offset) { return td_api_slot_tmq_offset_seek(tmq, pTopicName, vgId, offset); }

/* int64_t tmq_position(tmq_t *tmq, const char *pTopicName, int32_t vgId) */
static int64_t tmq_position_not_provided(tmq_t *tmq, const char *pTopicName, int32_t vgId) {
  tdApiNotProvided("tmq_position");
  return -1;
}
static __typeof__(&tmq_position) td_api_slot_tmq_position = tmq_position_not_provided;
int64_t tmq_position(tmq_t *tmq, const char *pTopicName, int32_t vgId) { return td_api_slot_tmq_position(tmq, pTopicName, vgId); }

/* int64_t tmq_committed(tmq_t *tmq, const char *pTopicName, int32_t vgId) */
static int64_t tmq_committed_not_provided(tmq_t *tmq, const char *pTopicName, int32_t vgId) {
  tdApiNotProvided("tmq_committed");
  return -1;
}
static __typeof__(&tmq_committed) td_api_slot_tmq_committed = tmq_committed_not_provided;
int64_t tmq_committed(tmq_t *tmq, const char *pTopicName, int32_t vgId) { return td_api_slot_tmq_committed(tmq, pTopicName, vgId); }

/* TAOS * tmq_get_connect(tmq_t *tmq) */
static TAOS * tmq_get_connect_not_provided(tmq_t *tmq) {
  tdApiNotProvided("tmq_get_connect");
  return NULL;
}
static __typeof__(&tmq_get_connect) td_api_slot_tmq_get_connect = tmq_get_connect_not_provided;
TAOS * tmq_get_connect(tmq_t *tmq) { return td_api_slot_tmq_get_connect(tmq); }

/* const char * tmq_get_table_name(TAOS_RES *res) */
static const char * tmq_get_table_name_not_provided(TAOS_RES *res) {
  tdApiNotProvided("tmq_get_table_name");
  return NULL;
}
static __typeof__(&tmq_get_table_name) td_api_slot_tmq_get_table_name = tmq_get_table_name_not_provided;
const char * tmq_get_table_name(TAOS_RES *res) { return td_api_slot_tmq_get_table_name(res); }

/* tmq_res_t tmq_get_res_type(TAOS_RES *res) */
static tmq_res_t tmq_get_res_type_not_provided(TAOS_RES *res) {
  tdApiNotProvided("tmq_get_res_type");
  return -1;
}
static __typeof__(&tmq_get_res_type) td_api_slot_tmq_get_res_type = tmq_get_res_type_not_provided;
tmq_res_t tmq_get_res_type(TAOS_RES *res) { return td_api_slot_tmq_get_res_type(res); }

/* const char * tmq_get_topic_name(TAOS_RES *res) */
static const char * tmq_get_topic_name_not_provided(TAOS_RES *res) {
  tdApiNotProvided("tmq_get_topic_name");
  return NULL;
}
static __typeof__(&tmq_get_topic_name) td_api_slot_tmq_get_topic_name = tmq_get_topic_name_not_provided;
const char * tmq_get_topic_name(TAOS_RES *res) { return td_api_slot_tmq_get_topic_name(res); }

/* const char * tmq_get_db_name(TAOS_RES *res) */
static const char * tmq_get_db_name_not_provided(TAOS_RES *res) {
  tdApiNotProvided("tmq_get_db_name");
  return NULL;
}
static __typeof__(&tmq_get_db_name) td_api_slot_tmq_get_db_name = tmq_get_db_name_not_provided;
const char * tmq_get_db_name(TAOS_RES *res) { return td_api_slot_tmq_get_db_name(res); }

/* int32_t tmq_get_vgroup_id(TAOS_RES *res) */
static int32_t tmq_get_vgroup_id_not_provided(TAOS_RES *res) {
  tdApiNotProvided("tmq_get_vgroup_id");
  return -1;
}
static __typeof__(&tmq_get_vgroup_id) td_api_slot_tmq_get_vgroup_id = tmq_get_vgroup_id_not_provided;
int32_t tmq_get_vgroup_id(TAOS_RES *res) { return td_api_slot_tmq_get_vgroup_id(res); }

/* int64_t tmq_get_vgroup_offset(TAOS_RES *res) */
static int64_t tmq_get_vgroup_offset_not_provided(TAOS_RES *res) {
  tdApiNotProvided("tmq_get_vgroup_offset");
  return -1;
}
static __typeof__(&tmq_get_vgroup_offset) td_api_slot_tmq_get_vgroup_offset = tmq_get_vgroup_offset_not_provided;
int64_t tmq_get_vgroup_offset(TAOS_RES *res) { return td_api_slot_tmq_get_vgroup_offset(res); }

/* const char * tmq_err2str(int32_t code) */
static const char * tmq_err2str_not_provided(int32_t code) {
  tdApiNotProvided("tmq_err2str");
  return NULL;
}
static __typeof__(&tmq_err2str) td_api_slot_tmq_err2str = tmq_err2str_not_provided;
const char * tmq_err2str(int32_t code) { return td_api_slot_tmq_err2str(code); }

/* int32_t tmq_get_raw(TAOS_RES *res, tmq_raw_data *raw) */
static int32_t tmq_get_raw_not_provided(TAOS_RES *res, tmq_raw_data *raw) {
  tdApiNotProvided("tmq_get_raw");
  return -1;
}
static __typeof__(&tmq_get_raw) td_api_slot_tmq_get_raw = tmq_get_raw_not_provided;
int32_t tmq_get_raw(TAOS_RES *res, tmq_raw_data *raw) { return td_api_slot_tmq_get_raw(res, raw); }

/* int32_t tmq_write_raw(TAOS *taos, tmq_raw_data raw) */
static int32_t tmq_write_raw_not_provided(TAOS *taos, tmq_raw_data raw) {
  tdApiNotProvided("tmq_write_raw");
  return -1;
}
static __typeof__(&tmq_write_raw) td_api_slot_tmq_write_raw = tmq_write_raw_not_provided;
int32_t tmq_write_raw(TAOS *taos, tmq_raw_data raw) { return td_api_slot_tmq_write_raw(taos, raw); }

/* int taos_write_raw_block(TAOS *taos, int numOfRows, char *pData, const char *tbname) */
static int taos_write_raw_block_not_provided(TAOS *taos, int numOfRows, char *pData, const char *tbname) {
  tdApiNotProvided("taos_write_raw_block");
  return -1;
}
static __typeof__(&taos_write_raw_block) td_api_slot_taos_write_raw_block = taos_write_raw_block_not_provided;
int taos_write_raw_block(TAOS *taos, int numOfRows, char *pData, const char *tbname) { return td_api_slot_taos_write_raw_block(taos, numOfRows, pData, tbname); }

/* int taos_write_raw_block_with_reqid(TAOS *taos, int numOfRows, char *pData, const char *tbname, int64_t reqid) */
static int taos_write_raw_block_with_reqid_not_provided(TAOS *taos, int numOfRows, char *pData, const char *tbname, int64_t reqid) {
  tdApiNotProvided("taos_write_raw_block_with_reqid");
  return -1;
}
static __typeof__(&taos_write_raw_block_with_reqid) td_api_slot_taos_write_raw_block_with_reqid = taos_write_raw_block_with_reqid_not_provided;
int taos_write_raw_block_with_reqid(TAOS *taos, int numOfRows, char *pData, const char *tbname, int64_t reqid) { return td_api_slot_taos_write_raw_block_with_reqid(taos, numOfRows, pData, tbname, reqid); }

/* int taos_write_raw_block_with_fields(TAOS *taos, int rows, char *pData, const char *tbname, TAOS_FIELD *fields, int numFields) */
static int taos_write_raw_block_with_fields_not_provided(TAOS *taos, int rows, char *pData, const char *tbname, TAOS_FIELD *fields, int numFields) {
  tdApiNotProvided("taos_write_raw_block_with_fields");
  return -1;
}
static __typeof__(&taos_write_raw_block_with_fields) td_api_slot_taos_write_raw_block_with_fields = taos_write_raw_block_with_fields_not_provided;
int taos_write_raw_block_with_fields(TAOS *taos, int rows, char *pData, const char *tbname, TAOS_FIELD *fields, int numFields) { return td_api_slot_taos_write_raw_block_with_fields(taos, rows, pData, tbname, fields, numFields); }

/* int taos_write_raw_block_with_fields_with_reqid(TAOS *taos, int rows, char *pData, const char *tbname, TAOS_FIELD *fields, int numFields, int64_t reqid) */
static int taos_write_raw_block_with_fields_with_reqid_not_provided(TAOS *taos, int rows, char *pData, const char *tbname, TAOS_FIELD *fields, int numFields, int64_t reqid) {
  tdApiNotProvided("taos_write_raw_block_with_fields_with_reqid");
  return -1;
}
static __typeof__(&taos_write_raw_block_with_fields_with_reqid) td_api_slot_taos_write_raw_block_with_fields_with_reqid = taos_write_raw_block_with_fields_with_reqid_not_provided;
int taos_write_raw_block_with_fields_with_reqid(TAOS *taos, int rows, char *pData, const char *tbname, TAOS_FIELD *fields, int numFields, int64_t reqid) { return td_api_slot_taos_write_raw_block_with_fields_with_reqid(taos, rows, pData, tbname, fields, numFields, reqid); }

/* void tmq_free_raw(tmq_raw_data raw) */
static void tmq_free_raw_not_provided(tmq_raw_data raw) { tdApiNotProvided("tmq_free_raw"); }
static __typeof__(&tmq_free_raw) td_api_slot_tmq_free_raw = tmq_free_raw_not_provided;
void tmq_free_raw(tmq_raw_data raw) { td_api_slot_tmq_free_raw(raw); }

/* char * tmq_get_json_meta(TAOS_RES *res) */
static char * tmq_get_json_meta_not_provided(TAOS_RES *res) {
  tdApiNotProvided("tmq_get_json_meta");
  return NULL;
}
static __typeof__(&tmq_get_json_meta) td_api_slot_tmq_get_json_meta = tmq_get_json_meta_not_provided;
char * tmq_get_json_meta(TAOS_RES *res) { return td_api_slot_tmq_get_json_meta(res); }

/* void tmq_free_json_meta(char *jsonMeta) */
static void tmq_free_json_meta_not_provided(char *jsonMeta) { tdApiNotProvided("tmq_free_json_meta"); }
static __typeof__(&tmq_free_json_meta) td_api_slot_tmq_free_json_meta = tmq_free_json_meta_not_provided;
void tmq_free_json_meta(char *jsonMeta) { td_api_slot_tmq_free_json_meta(jsonMeta); }

/* int32_t taos_connect_is_alive(TAOS *taos) */
static int32_t taos_connect_is_alive_not_provided(TAOS *taos) {
  tdApiNotProvided("taos_connect_is_alive");
  return -1;
}
static __typeof__(&taos_connect_is_alive) td_api_slot_taos_connect_is_alive = taos_connect_is_alive_not_provided;
int32_t taos_connect_is_alive(TAOS *taos) { return td_api_slot_taos_connect_is_alive(taos); }

/* TSDB_SERVER_STATUS taos_check_server_status(const char *fqdn, int port, char *details, int maxlen) */
static TSDB_SERVER_STATUS taos_check_server_status_not_provided(const char *fqdn, int port, char *details, int maxlen) {
  tdApiNotProvided("taos_check_server_status");
  return -1;
}
static __typeof__(&taos_check_server_status) td_api_slot_taos_check_server_status = taos_check_server_status_not_provided;
TSDB_SERVER_STATUS taos_check_server_status(const char *fqdn, int port, char *details, int maxlen) { return td_api_slot_taos_check_server_status(fqdn, port, details, maxlen); }

/* void taos_write_crashinfo(int signum, void *sigInfo, void *context) */
static void taos_write_crashinfo_not_provided(int signum, void *sigInfo, void *context) { tdApiNotProvided("taos_write_crashinfo"); }
static __typeof__(&taos_write_crashinfo) td_api_slot_taos_write_crashinfo = taos_write_crashinfo_not_provided;
void taos_write_crashinfo(int signum, void *sigInfo, void *context) { td_api_slot_taos_write_crashinfo(signum, sigInfo, context); }

/* char * getBuildInfo(void) */
static char * getBuildInfo_not_provided(void) {
  tdApiNotProvided("getBuildInfo");
  return NULL;
}
static __typeof__(&getBuildInfo) td_api_slot_getBuildInfo = getBuildInfo_not_provided;
char * getBuildInfo(void) { return td_api_slot_getBuildInfo(); }

/* int32_t taos_register_instance(const char *id, const char *type, const char *desc, int32_t expire) */
static int32_t taos_register_instance_not_provided(const char *id, const char *type, const char *desc, int32_t expire) {
  tdApiNotProvided("taos_register_instance");
  return -1;
}
static __typeof__(&taos_register_instance) td_api_slot_taos_register_instance = taos_register_instance_not_provided;
int32_t taos_register_instance(const char *id, const char *type, const char *desc, int32_t expire) { return td_api_slot_taos_register_instance(id, type, desc, expire); }

/* int32_t taos_list_instances(const char *filter_type, char ***pList, int32_t *pCount) */
static int32_t taos_list_instances_not_provided(const char *filter_type, char ***pList, int32_t *pCount) {
  tdApiNotProvided("taos_list_instances");
  return -1;
}
static __typeof__(&taos_list_instances) td_api_slot_taos_list_instances = taos_list_instances_not_provided;
int32_t taos_list_instances(const char *filter_type, char ***pList, int32_t *pCount) { return td_api_slot_taos_list_instances(filter_type, pList, pCount); }

/* void taos_free_instances(char ***pList, int32_t pCount) */
static void taos_free_instances_not_provided(char ***pList, int32_t pCount) { tdApiNotProvided("taos_free_instances"); }
static __typeof__(&taos_free_instances) td_api_slot_taos_free_instances = taos_free_instances_not_provided;
void taos_free_instances(char ***pList, int32_t pCount) { td_api_slot_taos_free_instances(pList, pCount); }

/* The slots, for the one start-up pass that fills them. */
static const TdApiSlot tdApiSlots[] = {
    { "taos_set_config", (void **)&td_api_slot_taos_set_config },
    { "taos_init", (void **)&td_api_slot_taos_init },
    { "taos_cleanup", (void **)&td_api_slot_taos_cleanup },
    { "taos_options", (void **)&td_api_slot_taos_options },
    { "taos_options_connection", (void **)&td_api_slot_taos_options_connection },
    { "taos_set_option", (void **)&td_api_slot_taos_set_option },
    { "taos_connect", (void **)&td_api_slot_taos_connect },
    { "taos_connect_auth", (void **)&td_api_slot_taos_connect_auth },
    { "taos_connect_with", (void **)&td_api_slot_taos_connect_with },
    { "taos_connect_with_dsn", (void **)&td_api_slot_taos_connect_with_dsn },
    { "taos_connect_totp", (void **)&td_api_slot_taos_connect_totp },
    { "taos_connect_test", (void **)&td_api_slot_taos_connect_test },
    { "taos_connect_token", (void **)&td_api_slot_taos_connect_token },
    { "taos_close", (void **)&td_api_slot_taos_close },
    { "taos_txn_begin", (void **)&td_api_slot_taos_txn_begin },
    { "taos_txn_commit", (void **)&td_api_slot_taos_txn_commit },
    { "taos_txn_rollback", (void **)&td_api_slot_taos_txn_rollback },
    { "taos_data_type", (void **)&td_api_slot_taos_data_type },
    { "taos_stmt_init", (void **)&td_api_slot_taos_stmt_init },
    { "taos_stmt_init_with_reqid", (void **)&td_api_slot_taos_stmt_init_with_reqid },
    { "taos_stmt_init_with_options", (void **)&td_api_slot_taos_stmt_init_with_options },
    { "taos_stmt_prepare", (void **)&td_api_slot_taos_stmt_prepare },
    { "taos_stmt_set_tbname_tags", (void **)&td_api_slot_taos_stmt_set_tbname_tags },
    { "taos_stmt_set_tbname", (void **)&td_api_slot_taos_stmt_set_tbname },
    { "taos_stmt_set_tags", (void **)&td_api_slot_taos_stmt_set_tags },
    { "taos_stmt_set_sub_tbname", (void **)&td_api_slot_taos_stmt_set_sub_tbname },
    { "taos_stmt_get_tag_fields", (void **)&td_api_slot_taos_stmt_get_tag_fields },
    { "taos_stmt_get_col_fields", (void **)&td_api_slot_taos_stmt_get_col_fields },
    { "taos_stmt_reclaim_fields", (void **)&td_api_slot_taos_stmt_reclaim_fields },
    { "taos_stmt_is_insert", (void **)&td_api_slot_taos_stmt_is_insert },
    { "taos_stmt_num_params", (void **)&td_api_slot_taos_stmt_num_params },
    { "taos_stmt_get_param", (void **)&td_api_slot_taos_stmt_get_param },
    { "taos_stmt_bind_param", (void **)&td_api_slot_taos_stmt_bind_param },
    { "taos_stmt_bind_param_batch", (void **)&td_api_slot_taos_stmt_bind_param_batch },
    { "taos_stmt_bind_single_param_batch", (void **)&td_api_slot_taos_stmt_bind_single_param_batch },
    { "taos_stmt_add_batch", (void **)&td_api_slot_taos_stmt_add_batch },
    { "taos_stmt_execute", (void **)&td_api_slot_taos_stmt_execute },
    { "taos_stmt_use_result", (void **)&td_api_slot_taos_stmt_use_result },
    { "taos_stmt_close", (void **)&td_api_slot_taos_stmt_close },
    { "taos_stmt_errstr", (void **)&td_api_slot_taos_stmt_errstr },
    { "taos_stmt_affected_rows", (void **)&td_api_slot_taos_stmt_affected_rows },
    { "taos_stmt_affected_rows_once", (void **)&td_api_slot_taos_stmt_affected_rows_once },
    { "taos_stmt2_init", (void **)&td_api_slot_taos_stmt2_init },
    { "taos_stmt2_prepare", (void **)&td_api_slot_taos_stmt2_prepare },
    { "taos_stmt2_bind_param", (void **)&td_api_slot_taos_stmt2_bind_param },
    { "taos_stmt2_bind_param_a", (void **)&td_api_slot_taos_stmt2_bind_param_a },
    { "taos_stmt2_bind_param_column", (void **)&td_api_slot_taos_stmt2_bind_param_column },
    { "taos_stmt2_bind_param_column_a", (void **)&td_api_slot_taos_stmt2_bind_param_column_a },
    { "taos_stmt2_exec", (void **)&td_api_slot_taos_stmt2_exec },
    { "taos_stmt2_close", (void **)&td_api_slot_taos_stmt2_close },
    { "taos_stmt2_is_insert", (void **)&td_api_slot_taos_stmt2_is_insert },
    { "taos_stmt2_get_fields", (void **)&td_api_slot_taos_stmt2_get_fields },
    { "taos_stmt2_free_fields", (void **)&td_api_slot_taos_stmt2_free_fields },
    { "taos_stmt2_result", (void **)&td_api_slot_taos_stmt2_result },
    { "taos_stmt2_error", (void **)&td_api_slot_taos_stmt2_error },
    { "taos_query", (void **)&td_api_slot_taos_query },
    { "taos_query_with_reqid", (void **)&td_api_slot_taos_query_with_reqid },
    { "taos_fetch_row", (void **)&td_api_slot_taos_fetch_row },
    { "taos_result_precision", (void **)&td_api_slot_taos_result_precision },
    { "taos_free_result", (void **)&td_api_slot_taos_free_result },
    { "taos_kill_query", (void **)&td_api_slot_taos_kill_query },
    { "taos_field_count", (void **)&td_api_slot_taos_field_count },
    { "taos_num_fields", (void **)&td_api_slot_taos_num_fields },
    { "taos_affected_rows", (void **)&td_api_slot_taos_affected_rows },
    { "taos_affected_rows64", (void **)&td_api_slot_taos_affected_rows64 },
    { "taos_fetch_fields", (void **)&td_api_slot_taos_fetch_fields },
    { "taos_fetch_fields_e", (void **)&td_api_slot_taos_fetch_fields_e },
    { "taos_select_db", (void **)&td_api_slot_taos_select_db },
    { "taos_print_row", (void **)&td_api_slot_taos_print_row },
    { "taos_print_row_with_size", (void **)&td_api_slot_taos_print_row_with_size },
    { "taos_stop_query", (void **)&td_api_slot_taos_stop_query },
    { "taos_is_null", (void **)&td_api_slot_taos_is_null },
    { "taos_is_null_by_column", (void **)&td_api_slot_taos_is_null_by_column },
    { "taos_is_update_query", (void **)&td_api_slot_taos_is_update_query },
    { "taos_fetch_block", (void **)&td_api_slot_taos_fetch_block },
    { "taos_fetch_block_s", (void **)&td_api_slot_taos_fetch_block_s },
    { "taos_fetch_raw_block", (void **)&td_api_slot_taos_fetch_raw_block },
    { "taos_get_column_data_offset", (void **)&td_api_slot_taos_get_column_data_offset },
    { "taos_validate_sql", (void **)&td_api_slot_taos_validate_sql },
    { "taos_reset_current_db", (void **)&td_api_slot_taos_reset_current_db },
    { "taos_fetch_lengths", (void **)&td_api_slot_taos_fetch_lengths },
    { "taos_result_block", (void **)&td_api_slot_taos_result_block },
    { "taos_get_server_info", (void **)&td_api_slot_taos_get_server_info },
    { "taos_get_client_info", (void **)&td_api_slot_taos_get_client_info },
    { "taos_get_current_db", (void **)&td_api_slot_taos_get_current_db },
    { "taos_get_connection_info", (void **)&td_api_slot_taos_get_connection_info },
    { "taos_get_result_tz", (void **)&td_api_slot_taos_get_result_tz },
    { "taos_errstr", (void **)&td_api_slot_taos_errstr },
    { "taos_errno", (void **)&td_api_slot_taos_errno },
    { "taos_query_a", (void **)&td_api_slot_taos_query_a },
    { "taos_query_a_with_reqid", (void **)&td_api_slot_taos_query_a_with_reqid },
    { "taos_fetch_rows_a", (void **)&td_api_slot_taos_fetch_rows_a },
    { "taos_fetch_raw_block_a", (void **)&td_api_slot_taos_fetch_raw_block_a },
    { "taos_get_raw_block", (void **)&td_api_slot_taos_get_raw_block },
    { "taos_get_db_route_info", (void **)&td_api_slot_taos_get_db_route_info },
    { "taos_get_table_vgId", (void **)&td_api_slot_taos_get_table_vgId },
    { "taos_get_tables_vgId", (void **)&td_api_slot_taos_get_tables_vgId },
    { "taos_load_table_info", (void **)&td_api_slot_taos_load_table_info },
    { "taos_set_hb_quit", (void **)&td_api_slot_taos_set_hb_quit },
    { "taos_set_notify_cb", (void **)&td_api_slot_taos_set_notify_cb },
    { "taos_fetch_whitelist_a", (void **)&td_api_slot_taos_fetch_whitelist_a },
    { "taos_fetch_whitelist_dual_stack_a", (void **)&td_api_slot_taos_fetch_whitelist_dual_stack_a },
    { "taos_fetch_ip_whitelist_a", (void **)&td_api_slot_taos_fetch_ip_whitelist_a },
    { "taos_fetch_datetime_whitelist_a", (void **)&td_api_slot_taos_fetch_datetime_whitelist_a },
    { "taos_set_conn_mode", (void **)&td_api_slot_taos_set_conn_mode },
    { "taos_schemaless_insert", (void **)&td_api_slot_taos_schemaless_insert },
    { "taos_schemaless_insert_with_reqid", (void **)&td_api_slot_taos_schemaless_insert_with_reqid },
    { "taos_schemaless_insert_raw", (void **)&td_api_slot_taos_schemaless_insert_raw },
    { "taos_schemaless_insert_raw_with_reqid", (void **)&td_api_slot_taos_schemaless_insert_raw_with_reqid },
    { "taos_schemaless_insert_ttl", (void **)&td_api_slot_taos_schemaless_insert_ttl },
    { "taos_schemaless_insert_ttl_with_reqid", (void **)&td_api_slot_taos_schemaless_insert_ttl_with_reqid },
    { "taos_schemaless_insert_raw_ttl", (void **)&td_api_slot_taos_schemaless_insert_raw_ttl },
    { "taos_schemaless_insert_raw_ttl_with_reqid", (void **)&td_api_slot_taos_schemaless_insert_raw_ttl_with_reqid },
    { "taos_schemaless_insert_raw_ttl_with_reqid_tbname_key", (void **)&td_api_slot_taos_schemaless_insert_raw_ttl_with_reqid_tbname_key },
    { "taos_schemaless_insert_ttl_with_reqid_tbname_key", (void **)&td_api_slot_taos_schemaless_insert_ttl_with_reqid_tbname_key },
    { "tmq_conf_new", (void **)&td_api_slot_tmq_conf_new },
    { "tmq_conf_set", (void **)&td_api_slot_tmq_conf_set },
    { "tmq_conf_destroy", (void **)&td_api_slot_tmq_conf_destroy },
    { "tmq_conf_set_auto_commit_cb", (void **)&td_api_slot_tmq_conf_set_auto_commit_cb },
    { "tmq_list_new", (void **)&td_api_slot_tmq_list_new },
    { "tmq_list_append", (void **)&td_api_slot_tmq_list_append },
    { "tmq_list_destroy", (void **)&td_api_slot_tmq_list_destroy },
    { "tmq_list_get_size", (void **)&td_api_slot_tmq_list_get_size },
    { "tmq_list_to_c_array", (void **)&td_api_slot_tmq_list_to_c_array },
    { "tmq_consumer_new", (void **)&td_api_slot_tmq_consumer_new },
    { "tmq_subscribe", (void **)&td_api_slot_tmq_subscribe },
    { "tmq_unsubscribe", (void **)&td_api_slot_tmq_unsubscribe },
    { "tmq_subscription", (void **)&td_api_slot_tmq_subscription },
    { "tmq_consumer_poll", (void **)&td_api_slot_tmq_consumer_poll },
    { "tmq_consumer_close", (void **)&td_api_slot_tmq_consumer_close },
    { "tmq_commit_sync", (void **)&td_api_slot_tmq_commit_sync },
    { "tmq_commit_async", (void **)&td_api_slot_tmq_commit_async },
    { "tmq_commit_offset_sync", (void **)&td_api_slot_tmq_commit_offset_sync },
    { "tmq_commit_offset_async", (void **)&td_api_slot_tmq_commit_offset_async },
    { "tmq_get_topic_assignment", (void **)&td_api_slot_tmq_get_topic_assignment },
    { "tmq_free_assignment", (void **)&td_api_slot_tmq_free_assignment },
    { "tmq_offset_seek", (void **)&td_api_slot_tmq_offset_seek },
    { "tmq_position", (void **)&td_api_slot_tmq_position },
    { "tmq_committed", (void **)&td_api_slot_tmq_committed },
    { "tmq_get_connect", (void **)&td_api_slot_tmq_get_connect },
    { "tmq_get_table_name", (void **)&td_api_slot_tmq_get_table_name },
    { "tmq_get_res_type", (void **)&td_api_slot_tmq_get_res_type },
    { "tmq_get_topic_name", (void **)&td_api_slot_tmq_get_topic_name },
    { "tmq_get_db_name", (void **)&td_api_slot_tmq_get_db_name },
    { "tmq_get_vgroup_id", (void **)&td_api_slot_tmq_get_vgroup_id },
    { "tmq_get_vgroup_offset", (void **)&td_api_slot_tmq_get_vgroup_offset },
    { "tmq_err2str", (void **)&td_api_slot_tmq_err2str },
    { "tmq_get_raw", (void **)&td_api_slot_tmq_get_raw },
    { "tmq_write_raw", (void **)&td_api_slot_tmq_write_raw },
    { "taos_write_raw_block", (void **)&td_api_slot_taos_write_raw_block },
    { "taos_write_raw_block_with_reqid", (void **)&td_api_slot_taos_write_raw_block_with_reqid },
    { "taos_write_raw_block_with_fields", (void **)&td_api_slot_taos_write_raw_block_with_fields },
    { "taos_write_raw_block_with_fields_with_reqid", (void **)&td_api_slot_taos_write_raw_block_with_fields_with_reqid },
    { "tmq_free_raw", (void **)&td_api_slot_tmq_free_raw },
    { "tmq_get_json_meta", (void **)&td_api_slot_tmq_get_json_meta },
    { "tmq_free_json_meta", (void **)&td_api_slot_tmq_free_json_meta },
    { "taos_connect_is_alive", (void **)&td_api_slot_taos_connect_is_alive },
    { "taos_check_server_status", (void **)&td_api_slot_taos_check_server_status },
    { "taos_write_crashinfo", (void **)&td_api_slot_taos_write_crashinfo },
    { "getBuildInfo", (void **)&td_api_slot_getBuildInfo },
    { "taos_register_instance", (void **)&td_api_slot_taos_register_instance },
    { "taos_list_instances", (void **)&td_api_slot_taos_list_instances },
    { "taos_free_instances", (void **)&td_api_slot_taos_free_instances },
    { NULL, NULL },
};

/* Called once, by the loader, right after the driver is loaded: every slot
 * gets the driver's entry point, or keeps its not-provided stub.  This is the
 * only place that pays a lookup per entry point. */
void tdApiInstallSlots(void) {
  const char *missing[8] = {0};
  int32_t     missingCount = 0;
  int32_t     total = 0;

  for (const TdApiSlot *entry = tdApiSlots; entry->name != NULL; ++entry) {
    ++total;
    void *fp = tdApiResolveLoaded(entry->name);
    if (fp == NULL) {
      if (missingCount < (int32_t)(sizeof(missing) / sizeof(missing[0]))) {
        missing[missingCount] = entry->name;
      }
      ++missingCount;
      continue;
    }
    *entry->slot = fp;
  }

  if (missingCount != 0) {
    /* Said once, here, instead of on the call path: the affected calls return
     * their failure value and report the name through tdApiNotProvided(). */
    fprintf(stderr, "taosadapter: %s does not provide %d of %d entry points",
            tdApiDriverPath()[0] == '\0' ? "the loaded driver" : tdApiDriverPath(), missingCount,
            total);
    for (int32_t i = 0; i < missingCount && i < (int32_t)(sizeof(missing) / sizeof(missing[0])); ++i) {
      fprintf(stderr, "%s%s", i == 0 ? ": " : ", ", missing[i]);
    }
    fprintf(stderr, "%s\n", missingCount > (int32_t)(sizeof(missing) / sizeof(missing[0])) ? ", ..." : "");
  }
}
